import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

const TAROT_DATA = [
  // MAJOR ARCANA (0-21)
  { card_name: "The Fool", card_number: 0, arcana_type: "Major", suit: null, upright_keywords: ["New beginnings", "Spontaneity", "Innocence"], reversed_keywords: ["Recklessness", "Folly", "Negligence"], upright_meaning: "The Fool represents a new beginning, a fresh start filled with optimism and potential. This card suggests embarking on a journey with faith and trust in the universe, embracing new experiences with childlike wonder.", reversed_meaning: "Reversed, The Fool warns of recklessness, poor judgment, or ignoring important warnings. It can indicate being taken advantage of or making foolish decisions.", key_symbols: [{ symbol: "The Cliff Edge", meaning: "Taking a leap of faith into the unknown" }, { symbol: "The Dog", meaning: "Instincts and protection" }, { symbol: "The Sun", meaning: "Optimism and new dawn" }] },
  { card_name: "The Magician", card_number: 1, arcana_type: "Major", suit: null, upright_keywords: ["Manifestation", "Resourcefulness", "Power"], reversed_keywords: ["Deception", "Misuse of power", "Untapped talents"], upright_meaning: "The Magician represents power, skill, and resourcefulness. This card indicates you have all the tools needed to manifest your desires and achieve your goals through focused intention and action.", reversed_meaning: "Reversed, The Magician suggests manipulation, deception, or misuse of personal power. It can indicate illusion, trickery, or failure to use your gifts effectively.", key_symbols: [{ symbol: "The Infinity Symbol", meaning: "Limitless potential and eternity" }, { symbol: "The Four Suits", meaning: "Mastery over all elements and resources" }, { symbol: "The Red Cloak", meaning: "Active will and divine will" }] },
  { card_name: "The High Priestess", card_number: 2, arcana_type: "Major", suit: null, upright_keywords: ["Intuition", "Mystery", "Knowledge"], reversed_keywords: ["Ignorance", "Lack of intuition", "Superficiality"], upright_meaning: "The High Priestess embodies intuition, sacred knowledge, and the mysteries of the subconscious. She urges you to trust your inner voice and seek deeper understanding beyond the material world.", reversed_meaning: "Reversed, The High Priestess suggests ignoring your intuition, hidden knowledge being withheld, or failing to trust your inner wisdom.", key_symbols: [{ symbol: "The Veil", meaning: "The boundary between the visible and invisible worlds" }, { symbol: "The Crescent Moon", meaning: "Intuition and feminine power" }, { symbol: "The Book of Knowledge", meaning: "Sacred wisdom and hidden truths" }] },
  { card_name: "The Empress", card_number: 3, arcana_type: "Major", suit: null, upright_keywords: ["Nurture", "Abundance", "Beauty"], reversed_keywords: ["Emptiness", "Dependence", "Infertility"], upright_meaning: "The Empress represents abundance, creativity, nurturing, and fertility. She embodies feminine power, compassion, and the creative force that brings things into being.", reversed_meaning: "Reversed, The Empress suggests creative blocks, feelings of emptiness, or unhealthy dependence on others.", key_symbols: [{ symbol: "The Crown", meaning: "Power and sovereignty" }, { symbol: "The Wheat Field", meaning: "Abundance and fertility" }, { symbol: "The Heart Scepter", meaning: "Love and compassion" }] },
  { card_name: "The Emperor", card_number: 4, arcana_type: "Major", suit: null, upright_keywords: ["Authority", "Control", "Leadership"], reversed_keywords: ["Weakness", "Tyranny", "Ineffectiveness"], upright_meaning: "The Emperor symbolizes authority, power, and leadership. He represents structure, discipline, and the ability to create order and stability through decisive action.", reversed_meaning: "Reversed, The Emperor can indicate weakness, tyranny, poor judgment, or abuse of power.", key_symbols: [{ symbol: "The Crown", meaning: "Authority and dominion" }, { symbol: "The Scepter", meaning: "Power of command" }, { symbol: "The Armor", meaning: "Strength and protection" }] },
  { card_name: "The Hierophant", card_number: 5, arcana_type: "Major", suit: null, upright_keywords: ["Tradition", "Morality", "Ethics"], reversed_keywords: ["Dogmatism", "Rebellion", "Unorthodoxy"], upright_meaning: "The Hierophant represents tradition, spiritual authority, and moral guidance. He suggests following established beliefs, seeking wisdom from mentors, or honoring spiritual practices.", reversed_meaning: "Reversed, The Hierophant indicates rejection of tradition, questioning authority, or breaking free from restrictive beliefs.", key_symbols: [{ symbol: "The Triple Cross", meaning: "Connection between divine and earthly realms" }, { symbol: "The Keys", meaning: "Access to hidden knowledge" }, { symbol: "The Robes", meaning: "Spiritual authority and tradition" }] },
  { card_name: "The Lovers", card_number: 6, arcana_type: "Major", suit: null, upright_keywords: ["Love", "Harmony", "Alignment"], reversed_keywords: ["Disharmony", "Misalignment", "Conflict"], upright_meaning: "The Lovers represents love, relationships, and harmony between opposites. It signifies alignment of values, meaningful connections, and important choices made from the heart.", reversed_meaning: "Reversed, The Lovers suggests disconnection, misalignment of values, or difficult relationship choices.", key_symbols: [{ symbol: "The Archangel", meaning: "Divine protection and blessing" }, { symbol: "The Naked Couple", meaning: "Vulnerability and authenticity" }, { symbol: "The Apple Tree", meaning: "Paradise and temptation" }] },
  { card_name: "The Chariot", card_number: 7, arcana_type: "Major", suit: null, upright_keywords: ["Control", "Direction", "Determination"], reversed_keywords: ["Loss of control", "Lack of direction", "Aggression"], upright_meaning: "The Chariot represents willpower, control, and moving forward with determination. It indicates victory achieved through self-discipline and focused effort.", reversed_meaning: "Reversed, The Chariot suggests loss of control, lack of direction, or aggressive behavior.", key_symbols: [{ symbol: "The Reins", meaning: "Control and direction" }, { symbol: "The Sphinxes", meaning: "Opposing forces in balance" }, { symbol: "The Stars", meaning: "Divine guidance" }] },
  { card_name: "Strength", card_number: 8, arcana_type: "Major", suit: null, upright_keywords: ["Inner strength", "Courage", "Patience"], reversed_keywords: ["Weakness", "Self-doubt", "Lack of control"], upright_meaning: "Strength represents inner fortitude, patience, and the gentle power of compassion. It shows that true strength comes from kindness, not force, and the ability to overcome challenges with grace.", reversed_meaning: "Reversed, Strength suggests self-doubt, weakness, or lack of control over circumstances.", key_symbols: [{ symbol: "The Lion", meaning: "Raw power and animal nature" }, { symbol: "The Wreath", meaning: "Victory and achievement" }, { symbol: "The Infinity Symbol", meaning: "Eternal strength" }] },
  { card_name: "The Hermit", card_number: 9, arcana_type: "Major", suit: null, upright_keywords: ["Introspection", "Wisdom", "Solitude"], reversed_keywords: ["Isolation", "Loneliness", "Lost wisdom"], upright_meaning: "The Hermit represents introspection, inner wisdom, and the journey inward. He suggests a period of solitude for reflection, self-discovery, and spiritual enlightenment.", reversed_meaning: "Reversed, The Hermit indicates unwanted isolation, loneliness, or withdrawal from necessary social connection.", key_symbols: [{ symbol: "The Lantern", meaning: "Inner light and guidance" }, { symbol: "The Staff", meaning: "Spiritual authority and wisdom" }, { symbol: "The Mountain", meaning: "Journey and enlightenment" }] },
  { card_name: "Wheel of Fortune", card_number: 10, arcana_type: "Major", suit: null, upright_keywords: ["Destiny", "Cycles", "Luck"], reversed_keywords: ["Bad luck", "Loss of control", "Resistance to change"], upright_meaning: "The Wheel of Fortune represents cycles, destiny, and the turning tides of fate. It signifies that change is inevitable and that good fortune is coming.", reversed_meaning: "Reversed, The Wheel suggests bad luck, loss of control, or resistance to necessary changes.", key_symbols: [{ symbol: "The Wheel", meaning: "Cycles and destiny" }, { symbol: "The Animals", meaning: "Different states of consciousness" }, { symbol: "The Serpent", meaning: "Descent into shadow" }] },
  { card_name: "Justice", card_number: 11, arcana_type: "Major", suit: null, upright_keywords: ["Justice", "Truth", "Balance"], reversed_keywords: ["Injustice", "Dishonesty", "Imbalance"], upright_meaning: "Justice represents fairness, truth, and accountability. It suggests that actions have consequences and that balance and equilibrium will be restored.", reversed_meaning: "Reversed, Justice indicates injustice, dishonesty, or facing the consequences of past actions.", key_symbols: [{ symbol: "The Scales", meaning: "Balance and impartiality" }, { symbol: "The Sword", meaning: "Truth and clarity" }, { symbol: "The Crown", meaning: "Authority and law" }] },
  { card_name: "The Hanged Man", card_number: 12, arcana_type: "Major", suit: null, upright_keywords: ["Suspension", "Perspective", "Letting go"], reversed_keywords: ["Resistance", "Unwillingness", "Stagnation"], upright_meaning: "The Hanged Man represents suspension, a new perspective, and surrender. It suggests pausing to gain wisdom, releasing old patterns, and viewing situations from a different angle.", reversed_meaning: "Reversed, The Hanged Man indicates resistance to change, unwillingness to release control, or stagnation.", key_symbols: [{ symbol: "The Noose", meaning: "Voluntary surrender" }, { symbol: "The Tree", meaning: "Life and wisdom" }, { symbol: "The Halo", meaning: "Spiritual enlightenment" }] },
  { card_name: "Death", card_number: 13, arcana_type: "Major", suit: null, upright_keywords: ["Endings", "Beginnings", "Transformation"], reversed_keywords: ["Resistance to change", "Stagnation", "Fear"], upright_meaning: "Death represents transformation, endings that lead to new beginnings, and necessary change. It is not literal death but the closing of one chapter to begin another.", reversed_meaning: "Reversed, Death suggests resistance to necessary change, stagnation, or fear of transformation.", key_symbols: [{ symbol: "The Skeleton", meaning: "Inevitable change" }, { symbol: "The White Horse", meaning: "Purity and new life" }, { symbol: "The Rising Sun", meaning: "Hope and rebirth" }] },
  { card_name: "Temperance", card_number: 14, arcana_type: "Major", suit: null, upright_keywords: ["Balance", "Moderation", "Harmony"], reversed_keywords: ["Imbalance", "Excess", "Conflict"], upright_meaning: "Temperance represents balance, moderation, and harmony between opposites. It suggests finding the middle path and blending different elements for optimal results.", reversed_meaning: "Reversed, Temperance indicates imbalance, excess, or conflict between opposing forces.", key_symbols: [{ symbol: "The Two Cups", meaning: "Blending of opposites" }, { symbol: "The Winged Angel", meaning: "Divine guidance and balance" }, { symbol: "The Triangle", meaning: "Spiritual alignment" }] },
  { card_name: "The Devil", card_number: 15, arcana_type: "Major", suit: null, upright_keywords: ["Bondage", "Materialism", "Shadow self"], reversed_keywords: ["Freedom", "Release", "Reclaiming power"], upright_meaning: "The Devil represents bondage, illusion, and the material world's hold over us. It indicates being trapped by habits, fears, or attachments that limit freedom.", reversed_meaning: "Reversed, The Devil suggests breaking free from bonds, gaining awareness, or reclaiming personal power.", key_symbols: [{ symbol: "The Chains", meaning: "Self-imposed limitations" }, { symbol: "The Pitchfork", meaning: "Temptation and desire" }, { symbol: "The Dark Figure", meaning: "Shadow aspects of self" }] },
  { card_name: "The Tower", card_number: 16, arcana_type: "Major", suit: null, upright_keywords: ["Chaos", "Destruction", "Sudden change"], reversed_keywords: ["Averted disaster", "Slow change", "Inner turmoil"], upright_meaning: "The Tower represents sudden change, disruption, and the breaking down of false structures. While challenging, it clears the way for necessary transformation and rebuilding.", reversed_meaning: "Reversed, The Tower suggests averted disaster, slower change, or maintaining a troubled situation.", key_symbols: [{ symbol: "The Lightning Bolt", meaning: "Sudden enlightenment" }, { symbol: "The Falling Figures", meaning: "Ego and illusion being destroyed" }, { symbol: "The Crown", meaning: "Illusions of power" }] },
  { card_name: "The Star", card_number: 17, arcana_type: "Major", suit: null, upright_keywords: ["Hope", "Guidance", "Inspiration"], reversed_keywords: ["Loss of hope", "Disappointment", "Lack of clarity"], upright_meaning: "The Star represents hope, inspiration, and divine guidance. It offers reassurance that clarity and purpose are returning, and your dreams are within reach.", reversed_meaning: "Reversed, The Star suggests loss of hope, disappointment, or lack of direction.", key_symbols: [{ symbol: "The Seven Stars", meaning: "Spiritual guidance and blessings" }, { symbol: "The Water", meaning: "Emotional truth and flow" }, { symbol: "The Maiden", meaning: "Hope and purity" }] },
  { card_name: "The Moon", card_number: 18, arcana_type: "Major", suit: null, upright_keywords: ["Intuition", "Illusion", "Dreams"], reversed_keywords: ["Clarity", "Exposure of truth", "Insight"], upright_meaning: "The Moon represents intuition, dreams, and the realm of the subconscious. It suggests trusting your instincts while being aware that not everything is as it seems.", reversed_meaning: "Reversed, The Moon indicates clarity returning, illusions being revealed, or emerging from confusion.", key_symbols: [{ symbol: "The Crescent Moon", meaning: "Intuition and inner vision" }, { symbol: "The Dogs", meaning: "Instincts and anxieties" }, { symbol: "The Path", meaning: "The journey through darkness" }] },
  { card_name: "The Sun", card_number: 19, arcana_type: "Major", suit: null, upright_keywords: ["Success", "Joy", "Clarity"], reversed_keywords: ["Negativity", "Disappointment", "Clouded judgment"], upright_meaning: "The Sun represents success, joy, clarity, and vitality. It indicates a time of happiness, achievement, and seeing things clearly in the light of truth.", reversed_meaning: "Reversed, The Sun suggests negativity, disappointment, or clouded judgment.", key_symbols: [{ symbol: "The Sunflower", meaning: "Growth and vitality" }, { symbol: "The Child", meaning: "Innocence and potential" }, { symbol: "The Wall", meaning: "Security and protection" }] },
  { card_name: "Judgement", card_number: 20, arcana_type: "Major", suit: null, upright_keywords: ["Reckoning", "Awakening", "Renewal"], reversed_keywords: ["Self-doubt", "Harsh self-criticism", "Doubt"], upright_meaning: "Judgement represents awakening, reckoning with past actions, and a call to a higher purpose. It signifies a moment of clarity and the need to answer an important calling.", reversed_meaning: "Reversed, Judgement suggests self-doubt, harsh self-criticism, or fear of judgment.", key_symbols: [{ symbol: "The Archangel", meaning: "Divine judgment and awakening" }, { symbol: "The Trumpet", meaning: "The call to action" }, { symbol: "The Bodies Rising", meaning: "Spiritual awakening and renewal" }] },
  { card_name: "The World", card_number: 21, arcana_type: "Major", suit: null, upright_keywords: ["Completion", "Wholeness", "Fulfillment"], reversed_keywords: ["Incompleteness", "Lack of closure", "Seeking"], upright_meaning: "The World represents completion, wholeness, and the fulfillment of a cycle. It indicates achievement of goals, integration of lessons, and moving to the next phase of life.", reversed_meaning: "Reversed, The World suggests incompleteness, lack of closure, or still seeking answers.", key_symbols: [{ symbol: "The Wreath", meaning: "Completion and success" }, { symbol: "The Four Creatures", meaning: "Integration of all elements" }, { symbol: "The Dancing Figure", meaning: "Joy and unity" }] },
];

// Helper to generate card_code
function generateCardCode(cardNumber, suit) {
  if (cardNumber < 22) {
    return `ar${String(cardNumber).padStart(2, '0')}`;
  }
  const suitMap = { 'Wands': 'wa', 'Cups': 'cu', 'Swords': 'sw', 'Pentacles': 'pe' };
  const minorNumber = cardNumber - 22 + 1;
  const suitCode = suitMap[suit] || 'wa';
  return `${suitCode}${String(minorNumber).padStart(2, '0')}`;
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Add card_code to each card
    const cardsWithCode = TAROT_DATA.map(card => ({
      ...card,
      card_code: generateCardCode(card.card_number, card.suit)
    }));

    // Delete existing
    const existing = await base44.asServiceRole.entities.TarotCard.list("-updated_date", 100);
    for (const card of existing) {
      await base44.asServiceRole.entities.TarotCard.delete(card.id);
    }

    // Create all cards
    await base44.asServiceRole.entities.TarotCard.bulkCreate(cardsWithCode);

    return Response.json({ success: true, message: `Seeded ${cardsWithCode.length} tarot cards with dynamic image URLs` });
  } catch (error) {
    console.error('Seed error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});