export const chakras = [
  {
    id: "root",
    name: "Root Chakra",
    sanskrit: "Muladhara",
    emoji: "🔴",
    color: "#ef4444",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/20",
    location: "Base of spine",
    element: "Earth",
    frequency: "396 Hz",
    mantra: "LAM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/94cce4e8b_Gemini_Generated_Image_x8sgvux8sgvux8sg.png",
    affirmation: "I am safe, grounded, and secure in this world.",
    balanced: "Feeling grounded, secure, stable, and physically healthy. Strong connection to body and earth.",
    blocks: [
      "Childhood trauma or neglect",
      "Financial instability or poverty consciousness",
      "Feeling unsafe in your environment",
      "Loss of home, family, or sense of belonging",
      "Generational or ancestral trauma",
      "Disconnection from the physical body",
    ],
    stagnant_symptoms: [
      "Chronic anxiety and free-floating fear",
      "Inability to feel safe or settled anywhere",
      "Persistent financial stress or scarcity mindset",
      "Lower back pain, hip tightness, leg problems",
      "Feeling 'spacey,' ungrounded, or unreal",
      "Difficulty completing tasks or staying present",
    ],
    overactive_symptoms: [
      "Greed, hoarding, or extreme materialism",
      "Aggression, rigidity, and resistance to change",
      "Obsession with physical security and control",
      "Overeating or excessive attachment to comfort",
      "Domineering or territorial behavior",
    ],
    healing: {
      crystal: "Black Tourmaline — place at the base of your spine during meditation or carry in your left pocket to absorb fear and anchor your energy to the earth.",
      herb: "Dandelion Root — brew as a tea each morning to stimulate grounding energy, strengthen roots, and connect with earth's nourishing frequency.",
      scent: "Patchouli or Cedarwood — diffuse, anoint your wrists and soles of your feet, or burn as incense to instantly anchor scattered energy.",
      color: "Wear red or carry something red throughout the day — even a red stone, ribbon, or garment activates the root's protective, stabilizing frequency.",
    },
    foods: ["Root vegetables (beets, carrots, potatoes)", "Red fruits (apples, strawberries)", "Protein-rich foods", "Earthy spices (turmeric, paprika)"],
    colors: ["Red", "Brown", "Black"],
    crystals: ["Black Tourmaline", "Red Jasper", "Obsidian", "Garnet"],
    yogaPoses: ["Mountain Pose (Tadasana)", "Warrior I (Virabhadrasana I)", "Child's Pose (Balasana)", "Malasana (Garland Pose)"],
  },
  {
    id: "sacral",
    name: "Sacral Chakra",
    sanskrit: "Svadhisthana",
    emoji: "🟠",
    color: "#f97316",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/20",
    location: "Lower abdomen",
    element: "Water",
    frequency: "417 Hz",
    mantra: "VAM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/3a76c9f80_Gemini_Generated_Image_tawzddtawzddtawz.png",
    affirmation: "I embrace pleasure, creativity, and the flow of life.",
    balanced: "Creative, passionate, emotionally healthy, comfortable with intimacy, joyful expression.",
    blocks: [
      "Shame around sexuality or pleasure",
      "Emotional abuse or manipulation",
      "Suppression of creative expression",
      "Guilt instilled by religion or culture",
      "Betrayal in intimate relationships",
      "Repressed emotions or feelings of unworthiness",
    ],
    stagnant_symptoms: [
      "Creative blocks and inability to feel inspired",
      "Emotional numbness or detachment",
      "Low libido or fear of intimacy",
      "Hip pain, lower back tightness, reproductive issues",
      "Feeling stuck, rigid, or resistant to flow",
      "Difficulty experiencing joy or pleasure",
    ],
    overactive_symptoms: [
      "Emotional dependency and clinginess",
      "Addictive patterns (food, substances, relationships)",
      "Obsessive attachments or possessiveness",
      "Dramatic mood swings and emotional flooding",
      "Overindulgence in pleasure or escapism",
    ],
    healing: {
      crystal: "Carnelian — hold over your lower abdomen or wear as jewelry to ignite creative fire, restore emotional flow, and awaken passion.",
      herb: "Damiana or Hibiscus — brew as a tea to honor the body's pleasure, stimulate creative energy, and gently dissolve emotional blockages.",
      scent: "Sweet Orange or Ylang Ylang — diffuse or apply diluted to the lower belly to awaken sensuality, creativity, and emotional openness.",
      color: "Wear or surround yourself with orange — from clothing to candles to artwork — to activate flow, joy, and creative vitality throughout the day.",
    },
    foods: ["Orange foods (oranges, mangos, carrots)", "Seeds and nuts", "Honey", "Coconut"],
    colors: ["Orange", "Coral"],
    crystals: ["Carnelian", "Orange Calcite", "Tiger's Eye", "Moonstone"],
    yogaPoses: ["Goddess Pose", "Pigeon Pose", "Bound Angle Pose", "Hip circles"],
  },
  {
    id: "solar",
    name: "Solar Plexus Chakra",
    sanskrit: "Manipura",
    emoji: "🟡",
    color: "#eab308",
    bgColor: "bg-yellow-500/10",
    borderColor: "border-yellow-500/20",
    location: "Upper abdomen",
    element: "Fire",
    frequency: "528 Hz",
    mantra: "RAM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/4d8a2c7e4_Gemini_Generated_Image_m3pg7am3pg7am3pg.png",
    affirmation: "I am powerful, confident, and in control of my destiny.",
    balanced: "Strong sense of self, confident, decisive, responsible, healthy willpower and personal authority.",
    blocks: [
      "Criticism, humiliation, or constant belittling in childhood",
      "Controlling or domineering relationships",
      "Failure without support or encouragement",
      "Lack of autonomy or personal choice",
      "Toxic power dynamics at work or home",
      "Internalized shame about personal power",
    ],
    stagnant_symptoms: [
      "Chronic low self-esteem and self-doubt",
      "Digestive issues, IBS, or stomach tension",
      "Inability to make decisions or assert yourself",
      "Victim mentality or learned helplessness",
      "Lack of motivation or drive",
      "Feeling powerless in your own life",
    ],
    overactive_symptoms: [
      "Controlling, domineering, or bullying behavior",
      "Perfectionism and harsh self-criticism",
      "Rage, arrogance, or need to always be right",
      "Workaholic tendencies or burnout",
      "Inability to accept help or vulnerability",
    ],
    healing: {
      crystal: "Citrine — place on your solar plexus during meditation or keep on your desk to amplify confidence, personal power, and manifestation energy.",
      herb: "Ginger Root — drink as a warm tea or add to meals to fire up your personal power center, strengthen digestion, and ignite confidence.",
      scent: "Lemon or Bergamot — diffuse in the morning or inhale before challenging situations to boost clarity, courage, and self-assurance.",
      color: "Wear yellow or gold — a yellow top, gold jewelry, or carry a sunstone — to radiate solar energy and affirm your personal power throughout the day.",
    },
    foods: ["Yellow foods (bananas, corn, pineapple)", "Whole grains", "Ginger and turmeric", "Chamomile tea"],
    colors: ["Yellow", "Gold"],
    crystals: ["Citrine", "Yellow Jasper", "Tiger's Eye", "Amber"],
    yogaPoses: ["Boat Pose (Navasana)", "Warrior III", "Sun Salutations", "Twisted Chair Pose"],
  },
  {
    id: "heart",
    name: "Heart Chakra",
    sanskrit: "Anahata",
    emoji: "💚",
    color: "#22c55e",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/20",
    location: "Center of chest",
    element: "Air",
    frequency: "639 Hz",
    mantra: "YAM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/e2b81e0ed_Gemini_Generated_Image_lnporjlnporjlnpo.png",
    affirmation: "I give and receive love freely and unconditionally.",
    balanced: "Loving, compassionate, empathetic, forgiving, peaceful relationships, emotional resilience.",
    blocks: [
      "Grief, loss, and unprocessed heartbreak",
      "Betrayal or abandonment by loved ones",
      "Growing up in a loveless or critical environment",
      "Unforgiveness toward self or others",
      "Chronic loneliness or isolation",
      "Self-sacrifice without receiving in return",
    ],
    stagnant_symptoms: [
      "Chest tightness, heart palpitations, or shallow breathing",
      "Inability to trust or open up to others",
      "Deep loneliness even when surrounded by people",
      "Grief that won't move or be released",
      "Compassion fatigue or emotional shutdown",
      "Difficulty receiving love or compliments",
    ],
    overactive_symptoms: [
      "Codependency and losing yourself in others",
      "People-pleasing at the expense of your needs",
      "Jealousy, possessiveness, or smothering love",
      "Inability to set healthy boundaries",
      "Constant self-sacrifice leading to resentment",
    ],
    healing: {
      crystal: "Rose Quartz — hold over your heart center or sleep with it under your pillow to gently dissolve grief, invite self-love, and open to receive love.",
      herb: "Hawthorn Berry or Rose Petal — brew as a heart-opening tea to soothe grief, nourish emotional resilience, and restore trust in love.",
      scent: "Rose or Geranium — apply over your heart space or diffuse during self-care rituals to soften grief, expand compassion, and invite tenderness.",
      color: "Wear green or pink throughout the day — carry a rose quartz in your bra or pocket, wear green clothing, or bring fresh flowers into your space.",
    },
    foods: ["Green vegetables (kale, spinach, broccoli)", "Green tea", "Avocado", "Rose tea"],
    colors: ["Green", "Pink"],
    crystals: ["Rose Quartz", "Green Aventurine", "Malachite", "Jade"],
    yogaPoses: ["Camel Pose (Ustrasana)", "Cobra Pose", "Bridge Pose", "Eagle Pose"],
  },
  {
    id: "throat",
    name: "Throat Chakra",
    sanskrit: "Vishuddha",
    emoji: "🔵",
    color: "#3b82f6",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    location: "Throat",
    element: "Ether",
    frequency: "741 Hz",
    mantra: "HAM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/7abcb5060_Gemini_Generated_Image_vcasv5vcasv5vcas.png",
    affirmation: "I speak my truth with clarity, confidence, and compassion.",
    balanced: "Clear communication, authentic expression, good listening, living truthfully, creative voice.",
    blocks: [
      "Being silenced, dismissed, or punished for speaking up",
      "Secrets kept or lies told over long periods",
      "Verbal abuse or being told your voice doesn't matter",
      "Cultural or family suppression of authentic expression",
      "Fear of conflict or confrontation",
      "Not living in alignment with your truth",
    ],
    stagnant_symptoms: [
      "Chronic sore throat, thyroid imbalances, neck tension",
      "Difficulty saying what you really mean",
      "Fear of public speaking or being seen",
      "Swallowing your feelings to keep the peace",
      "Feeling chronically misunderstood",
      "Writer's block or creative voice suppression",
    ],
    overactive_symptoms: [
      "Talking excessively or dominating conversations",
      "Gossiping, harsh words, or verbal cruelty",
      "Inability to listen or receive others' truth",
      "Oversharing or inappropriate self-disclosure",
      "Lying or embellishing to feel powerful",
    ],
    healing: {
      crystal: "Lapis Lazuli — hold at your throat or wear as a necklace to activate truth-speaking, dissolve communication fear, and align your words with your soul.",
      herb: "Slippery Elm or Licorice Root — brew as a soothing throat tea to ease physical tension, support the thyroid, and smooth the path to authentic expression.",
      scent: "Eucalyptus or Peppermint — inhale or diffuse before important conversations or creative work to open airways, clear the mind, and sharpen authentic voice.",
      color: "Wear blue or turquoise — a blue scarf near the throat, turquoise jewelry, or blue lace agate — to activate truthful, flowing communication all day.",
    },
    foods: ["Blueberries", "Herbal teas", "Honey", "Soups and liquids"],
    colors: ["Blue", "Turquoise"],
    crystals: ["Lapis Lazuli", "Aquamarine", "Sodalite", "Blue Lace Agate"],
    yogaPoses: ["Shoulder Stand", "Fish Pose", "Plow Pose", "Lion's Breath"],
  },
  {
    id: "third_eye",
    name: "Third Eye Chakra",
    sanskrit: "Ajna",
    emoji: "🟣",
    color: "#8b5cf6",
    bgColor: "bg-violet-500/10",
    borderColor: "border-violet-500/20",
    location: "Between eyebrows",
    element: "Light",
    frequency: "852 Hz",
    mantra: "OM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/27b5905b5_Gemini_Generated_Image_u56sgou56sgou56s.png",
    affirmation: "I trust my intuition and see the truth beyond illusion.",
    balanced: "Strong intuition, vivid imagination, clear thinking, spiritual awareness, insightful dreams.",
    blocks: [
      "Dismissing or doubting your own intuition",
      "Over-reliance on logic at the expense of inner knowing",
      "Spiritual trauma or disillusionment",
      "Living in survival mode without space for reflection",
      "Toxic environments that suppress spiritual curiosity",
      "Fear of what you might see if you truly look within",
    ],
    stagnant_symptoms: [
      "Confusion, brain fog, or inability to focus",
      "Recurring headaches or migraines",
      "Feeling directionless or without purpose",
      "Difficulty trusting your gut or making decisions",
      "Poor dream recall or disconnected dream life",
      "Inability to visualize or access imagination",
    ],
    overactive_symptoms: [
      "Overthinking, analysis paralysis, obsessive thoughts",
      "Nightmares, disturbing visions, or sleep disruption",
      "Living in your head and ignoring physical reality",
      "Hallucinations or distorted perception",
      "Spiritual arrogance or bypassing",
    ],
    healing: {
      crystal: "Amethyst — place on your third eye during meditation or keep on your nightstand to enhance intuition, promote clarity, and support prophetic dreaming.",
      herb: "Mugwort — burn as an incense, brew as a dream tea before bed, or place under your pillow to activate visionary states and strengthen psychic perception.",
      scent: "Frankincense or Clary Sage — diffuse during meditation or apply to the brow chakra to dissolve mental fog, deepen intuition, and open spiritual sight.",
      color: "Wear indigo or violet throughout the day — a purple stone, indigo fabric, or amethyst jewelry — to keep your third eye activated and your vision clear.",
    },
    foods: ["Purple foods (grapes, eggplant, blackberries)", "Dark chocolate", "Mugwort tea", "Omega-3 rich foods"],
    colors: ["Indigo", "Purple"],
    crystals: ["Amethyst", "Labradorite", "Fluorite", "Lapis Lazuli"],
    yogaPoses: ["Child's Pose with Third Eye press", "Eagle Pose", "Dolphin Pose", "Seated meditation"],
  },
  {
    id: "crown",
    name: "Crown Chakra",
    sanskrit: "Sahasrara",
    emoji: "⚪",
    color: "#a855f7",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    location: "Top of head",
    element: "Cosmic Energy",
    frequency: "963 Hz",
    mantra: "Silence / AUM",
    image: "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/69b4c0060553de697bc30fd6/1d4a4a80c_Gemini_Generated_Image_wimudtwimudtwimu.png",
    affirmation: "I am connected to the divine source of all creation.",
    balanced: "Spiritual connection, inner peace, sense of purpose, universal love, wisdom, enlightenment.",
    blocks: [
      "Rigid religious trauma or spiritual wounding",
      "Cynicism, materialism, or nihilistic beliefs",
      "Deep depression or existential emptiness",
      "Disconnection from anything greater than the self",
      "Overidentification with ego and physical identity",
      "Unresolved pain in the lower chakras cutting off divine flow",
    ],
    stagnant_symptoms: [
      "Feeling spiritually empty or abandoned by the divine",
      "Chronic depression, apathy, or meaninglessness",
      "Inability to access stillness or inner peace",
      "No sense of life purpose or soul direction",
      "Feeling isolated from humanity and the cosmos",
      "Learning difficulties or cognitive fog",
    ],
    overactive_symptoms: [
      "Spiritual addiction or bypassing earthly responsibilities",
      "Superiority complex or 'chosen one' delusions",
      "Complete disconnection from the physical body",
      "Neglecting basic physical needs (food, sleep, grounding)",
      "Inability to function in everyday reality",
    ],
    healing: {
      crystal: "Selenite — place a selenite wand above your head during meditation or on your crown to clear energetic debris, invite divine downloads, and restore cosmic connection.",
      herb: "Lavender or Lotus — brew as a calming tea or burn as incense to quiet the mind, dissolve the veil between you and the divine, and invite transcendent peace.",
      scent: "Sandalwood or Lotus — diffuse during prayer, meditation, or sacred rituals to elevate consciousness, dissolve ego boundaries, and open the channel to source.",
      color: "Wear white, violet, or gold — a white linen garment, selenite jewelry, or golden accessories — to align your energy field with the divine frequency of the crown.",
    },
    foods: ["Fasting/detox", "Pure water", "Incense/smudging", "Light, clean foods"],
    colors: ["Violet", "White", "Gold"],
    crystals: ["Clear Quartz", "Selenite", "Amethyst", "Diamond"],
    yogaPoses: ["Headstand (Sirsasana)", "Lotus Pose", "Savasana", "Meditation"],
  },
];