export const chakras = [
  {
    id: "root",
    name: "Root Chakra",
    sanskrit: "Muladhara",
    emoji: "🔴",
    color: "#ef4444",
    bgColor: "bg-red-500/10",
    borderColor: "border-red-500/20",
    location: "Base of spine",
    element: "Earth",
    frequency: "396 Hz",
    mantra: "LAM",
    affirmation: "I am safe, grounded, and secure in this world.",
    balanced: "Feeling grounded, secure, stable, and physically healthy. Strong connection to body and earth.",
    blocked: "Anxiety, fear, insecurity, financial stress, feeling ungrounded, lower back pain, immune issues.",
    overactive: "Greed, materialism, resistance to change, hoarding, aggression, controlling behavior.",
    underactive: "Disconnected, spacey, fearful, lacking stability, poor boundaries, weight issues.",
    foods: ["Root vegetables (beets, carrots, potatoes)", "Red fruits (apples, strawberries)", "Protein-rich foods", "Earthy spices (turmeric, paprika)"],
    colors: ["Red", "Brown", "Black"],
    crystals: ["Black Tourmaline", "Red Jasper", "Obsidian", "Garnet"],
    yogaPoses: ["Mountain Pose (Tadasana)", "Warrior I (Virabhadrasana I)", "Child's Pose (Balasana)", "Malasana (Garland Pose)"],
  },
  {
    id: "sacral",
    name: "Sacral Chakra",
    sanskrit: "Svadhisthana",
    emoji: "🟠",
    color: "#f97316",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/20",
    location: "Lower abdomen",
    element: "Water",
    frequency: "417 Hz",
    mantra: "VAM",
    affirmation: "I embrace pleasure, creativity, and the flow of life.",
    balanced: "Creative, passionate, emotionally healthy, comfortable with intimacy, joyful expression.",
    blocked: "Emotional numbness, low libido, creative blocks, guilt, fear of pleasure, hip/lower back pain.",
    overactive: "Emotional dependency, addiction, obsessive attachments, mood swings, overindulgence.",
    underactive: "Low energy, lack of creativity, emotional detachment, fear of change, rigidity.",
    foods: ["Orange foods (oranges, mangos, carrots)", "Seeds and nuts", "Honey", "Coconut"],
    colors: ["Orange", "Coral"],
    crystals: ["Carnelian", "Orange Calcite", "Tiger's Eye", "Moonstone"],
    yogaPoses: ["Goddess Pose", "Pigeon Pose", "Bound Angle Pose", "Hip circles"],
  },
  {
    id: "solar",
    name: "Solar Plexus Chakra",
    sanskrit: "Manipura",
    emoji: "🟡",
    color: "#eab308",
    bgColor: "bg-yellow-500/10",
    borderColor: "border-yellow-500/20",
    location: "Upper abdomen",
    element: "Fire",
    frequency: "528 Hz",
    mantra: "RAM",
    affirmation: "I am powerful, confident, and in control of my destiny.",
    balanced: "Strong sense of self, confident, decisive, responsible, healthy willpower and personal authority.",
    blocked: "Low self-esteem, powerlessness, indecisiveness, digestive issues, victim mentality.",
    overactive: "Controlling, perfectionism, anger, domination, workaholism, judgmental.",
    underactive: "Passive, unreliable, poor digestion, lack of ambition, constant self-doubt.",
    foods: ["Yellow foods (bananas, corn, pineapple)", "Whole grains", "Ginger and turmeric", "Chamomile tea"],
    colors: ["Yellow", "Gold"],
    crystals: ["Citrine", "Yellow Jasper", "Tiger's Eye", "Amber"],
    yogaPoses: ["Boat Pose (Navasana)", "Warrior III", "Sun Salutations", "Twisted Chair Pose"],
  },
  {
    id: "heart",
    name: "Heart Chakra",
    sanskrit: "Anahata",
    emoji: "💚",
    color: "#22c55e",
    bgColor: "bg-green-500/10",
    borderColor: "border-green-500/20",
    location: "Center of chest",
    element: "Air",
    frequency: "639 Hz",
    mantra: "YAM",
    affirmation: "I give and receive love freely and unconditionally.",
    balanced: "Loving, compassionate, empathetic, forgiving, peaceful relationships, emotional resilience.",
    blocked: "Grief, loneliness, jealousy, fear of intimacy, chest tightness, heart/lung issues.",
    overactive: "Codependency, people-pleasing, poor boundaries, jealousy, sacrificing self for others.",
    underactive: "Cold, distant, isolated, bitter, unable to trust, fear of rejection.",
    foods: ["Green vegetables (kale, spinach, broccoli)", "Green tea", "Avocado", "Rose tea"],
    colors: ["Green", "Pink"],
    crystals: ["Rose Quartz", "Green Aventurine", "Malachite", "Jade"],
    yogaPoses: ["Camel Pose (Ustrasana)", "Cobra Pose", "Bridge Pose", "Eagle Pose"],
  },
  {
    id: "throat",
    name: "Throat Chakra",
    sanskrit: "Vishuddha",
    emoji: "🔵",
    color: "#3b82f6",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    location: "Throat",
    element: "Ether",
    frequency: "741 Hz",
    mantra: "HAM",
    affirmation: "I speak my truth with clarity, confidence, and compassion.",
    balanced: "Clear communication, authentic expression, good listening, living truthfully, creative voice.",
    blocked: "Fear of speaking up, sore throat, thyroid issues, shyness, inability to express feelings.",
    overactive: "Gossiping, dominating conversations, inability to listen, harsh words, oversharing.",
    underactive: "Quiet, secretive, can't express needs, fear of judgment, feeling misunderstood.",
    foods: ["Blueberries", "Herbal teas", "Honey", "Soups and liquids"],
    colors: ["Blue", "Turquoise"],
    crystals: ["Lapis Lazuli", "Aquamarine", "Sodalite", "Blue Lace Agate"],
    yogaPoses: ["Shoulder Stand", "Fish Pose", "Plow Pose", "Lion's Breath"],
  },
  {
    id: "third_eye",
    name: "Third Eye Chakra",
    sanskrit: "Ajna",
    emoji: "🟣",
    color: "#8b5cf6",
    bgColor: "bg-violet-500/10",
    borderColor: "border-violet-500/20",
    location: "Between eyebrows",
    element: "Light",
    frequency: "852 Hz",
    mantra: "OM",
    affirmation: "I trust my intuition and see the truth beyond illusion.",
    balanced: "Strong intuition, vivid imagination, clear thinking, spiritual awareness, insightful dreams.",
    blocked: "Confusion, lack of purpose, poor memory, difficulty concentrating, headaches, denial.",
    overactive: "Overthinking, nightmares, hallucinations, obsessive fantasies, disconnected from reality.",
    underactive: "Poor intuition, rigid thinking, lack of imagination, inability to see the big picture.",
    foods: ["Purple foods (grapes, eggplant, blackberries)", "Dark chocolate", "Mugwort tea", "Omega-3 rich foods"],
    colors: ["Indigo", "Purple"],
    crystals: ["Amethyst", "Labradorite", "Fluorite", "Lapis Lazuli"],
    yogaPoses: ["Child's Pose with Third Eye press", "Eagle Pose", "Dolphin Pose", "Seated meditation"],
  },
  {
    id: "crown",
    name: "Crown Chakra",
    sanskrit: "Sahasrara",
    emoji: "⚪",
    color: "#a855f7",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    location: "Top of head",
    element: "Cosmic Energy",
    frequency: "963 Hz",
    mantra: "Silence / AUM",
    affirmation: "I am connected to the divine source of all creation.",
    balanced: "Spiritual connection, inner peace, sense of purpose, universal love, wisdom, enlightenment.",
    blocked: "Spiritual disconnection, cynicism, closed-mindedness, learning difficulties, depression.",
    overactive: "Spiritual addiction, disconnection from body, superiority complex, neglecting physical needs.",
    underactive: "Apathy, no sense of purpose, feeling disconnected from spirit, existential doubt.",
    foods: ["Fasting/detox", "Pure water", "Incense/smudging", "Light, clean foods"],
    colors: ["Violet", "White", "Gold"],
    crystals: ["Clear Quartz", "Selenite", "Amethyst", "Diamond"],
    yogaPoses: ["Headstand (Sirsasana)", "Lotus Pose", "Savasana", "Meditation"],
  },
];