export const libraryCrystals = [
  {
    name: "Amazonite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/amazonite/tumbled-amazonite-gemstone-amazon-stone-dark-macro-shooting-natural-mineral-rock-specimen-tumbled-amazonite-gemstone-amazon-103207551.webp",
    chakra: "Heart & Throat",
    element: "Water",
    zodiac: "Virgo",
    spiritual: "Amazonite is the stone of truth, courage, and communication. It soothes the nervous system and aligns the heart with the throat — helping you speak your deepest truth with compassion. It clears energetic blockages and dissolves fears around self-expression.",
    magical: "Used in spells for clarity of communication, manifesting personal truth, and soothing anxiety. Place on your throat chakra during meditation to unlock suppressed words. Carry to calm stress before difficult conversations.",
    folklore: "Named after the Amazon River, amazonite was carved into tablets bearing the Egyptian Book of the Dead. Ancient Egyptians set it in gold jewelry and used it in amulets. It was found adorning the armor and shields of Amazonian warrior women.",
  },
  {
    name: "Aquamarine",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/aquamarine/macro-mineral-stone-aquamarine-black-background_254845-6375.avif",
    chakra: "Throat & Heart",
    element: "Water",
    zodiac: "Pisces, Gemini, Aries",
    spiritual: "Aquamarine is the stone of courage, clarity, and calming truth. It cools the emotions, releases fear, and helps you speak your truth with gentleness and grace. A powerful ally for empaths, it shields the aura and promotes emotional balance in turbulent times.",
    magical: "Use in rituals for clarity of communication, releasing fear, and protection during travel — especially over water. Meditate with it at the throat to dissolve unexpressed grief. Place near water altars to amplify intention-setting during moon rituals.",
    folklore: "Ancient sailors carried aquamarine as a talisman of protection against storms and shipwrecks. Romans believed it was sacred to Neptune. It was also thought to make its wearer unconquerable in battle and to bring good luck to marriages.",
  },
  {
    name: "Black Obsidian",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/black+obsidian/1.webp",
    chakra: "Root",
    element: "Earth & Fire",
    zodiac: "Sagittarius, Scorpio",
    spiritual: "Black Obsidian is a volcanic glass of raw, unfiltered truth. It cuts through illusion, exposes shadow, and forces deep emotional reckoning. A stone of transformation and protection, it dissolves energetic cords and shields against psychic attack and negative energy.",
    magical: "Essential for shadow work and psychic protection. Use in scrying, place at the front door for protection, or carry when navigating toxic environments. Create a protective grid around your home or sacred space for powerful energetic shielding.",
    folklore: "Obsidian was used by ancient Aztecs and Mayans to craft ritual blades, mirrors for scrying, and ceremonial tools. The Aztec deity Tezcatlipoca carried an obsidian mirror to see into the hearts of men. It has been revered as a gateway to the underworld across many cultures.",
  },
  {
    name: "Black Tourmaline",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/black+tourmaline/360_F_663481336_qfo9b7soC2kEOv02KHiYGp10ILotsYVu.jpg",
    chakra: "Root",
    element: "Earth",
    zodiac: "Capricorn, Libra",
    spiritual: "Black Tourmaline is the ultimate protector. It creates an energetic forcefield around the body, repelling negativity, psychic intrusion, and electromagnetic pollution. It grounds scattered energy deeply into the Earth and transmutes dense, heavy vibrations into light.",
    magical: "Place at the four corners of your home to create a protection grid. Wear during conflict or in crowded spaces. Bury near your front door to block negative energy from entering. Use in banishing spells and cleansing rituals.",
    folklore: "In ancient times, tourmaline was believed to be a stone that fell from a rainbow, carrying all its colors. Black tourmaline specifically was used by shamanic practitioners in Africa, Australia, and Native American tribes for protection during vision quests and spirit work.",
  },
  {
    name: "Carnelian",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/carnelian/images.jpg",
    chakra: "Sacral & Root",
    element: "Fire",
    zodiac: "Aries, Taurus, Cancer",
    spiritual: "Carnelian is the stone of vitality, courage, and creative fire. It ignites passion, restores motivation, and anchors you in the present moment. A powerful ally for artists and dreamers, it dissolves creative blocks and fuels bold action toward your desires.",
    magical: "Use in spells for confidence, creativity, and sexuality. Carry when starting new projects or needing a surge of motivation. Place on the sacral chakra to awaken creative energy and sensuality. Burn orange candles alongside carnelian in passion rituals.",
    folklore: "Ancient Egyptians called carnelian 'the setting sun' and placed it in tombs for protection in the afterlife. Napoleon wore a carnelian seal ring. Islamic tradition holds that carnelian engraved with a prayer brings good fortune, and it was widely used in signet rings across the ancient world.",
  },
  {
    name: "Citrine",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/citrine/360_F_1171493078_fQmaVIe4YwqMZsUl57lPUlUE2vvKqwbc.jpg",
    chakra: "Solar Plexus",
    element: "Fire",
    zodiac: "Aries, Gemini, Leo, Libra",
    spiritual: "Citrine is the stone of light, abundance, and personal power. Known as the 'Merchant's Stone,' it attracts prosperity and success while radiating pure solar energy. It raises self-esteem, dissolves self-doubt, and helps you fully step into your power and purpose.",
    magical: "Place in your cash register or wallet to attract abundance. Use in prosperity rituals on the new moon. Carry to amplify joy and dissolve negativity — citrine is one of the few crystals that never needs cleansing, as it transmutes all energy into light.",
    folklore: "Citrine has been used as a talisman against snake venom and evil thoughts since ancient times. The Romans wore it in intaglio rings. In medieval Scotland, it was set into sword handles as a protection charm. Its golden color has long linked it to the sun and divine abundance.",
  },
  {
    name: "Clear Quartz",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/clear+quartz/download.jpg",
    chakra: "Crown (all chakras)",
    element: "All Elements",
    zodiac: "All Signs",
    spiritual: "Clear Quartz is the master healer and amplifier of the crystal world. It absorbs, stores, releases, and regulates energy. It aligns all chakras, amplifies the power of any intention, and acts as a bridge between the physical and spiritual realms. The ultimate all-purpose stone.",
    magical: "Program with any intention and it will amplify it tenfold. Place at the center of crystal grids to supercharge them. Use to cleanse and charge other crystals. Hold during meditation to heighten clarity and receive guidance. Pair with any other stone to boost its energy.",
    folklore: "Ancient cultures worldwide revered clear quartz as solidified light or divine ice. Australian Aboriginals used it in rain-making rituals. Japanese considered it the perfect jewel, symbolizing space, purity, and patience. Shamans across cultures used it as a scrying tool and conduit for spirit communication.",
  },
  {
    name: "Chrysocolla",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/crysocolla/chrysocolla-fossil-mineral-stone-geological-crystalline-fossil-dark-background-close-up-chrysocolla-fossil-mineral-stone-316396675.webp",
    chakra: "Throat, Heart & Root",
    element: "Water & Earth",
    zodiac: "Taurus, Gemini, Virgo",
    spiritual: "Chrysocolla is the stone of the divine feminine — the great teacher and communicator. It draws out guilt, heals heartbreak, and empowers authentic self-expression. It calms the emotional body, fosters inner strength through gentleness, and reconnects you with Earth's wisdom.",
    magical: "Use in rituals for forgiveness, emotional healing, and speaking sacred truths. Place on the heart and throat together during energy work. Carry when navigating difficult conversations or setting boundaries with love. Powerful ally for women reclaiming their voice.",
    folklore: "Cleopatra is said to have always worn chrysocolla and carried it with her everywhere. The ancients believed it was a stone of wise women and prophetesses. In Peru, it was called the 'wise stone' and used by healers. King Solomon wore it for wisdom in negotiations.",
  },
  {
    name: "Fluorite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Fluorite/fluorite-crystal-black-background-high-quality-photo-303234001.webp",
    chakra: "Third Eye & Heart",
    element: "Air & Water",
    zodiac: "Capricorn, Pisces",
    spiritual: "Fluorite is the genius stone — a supreme mental clarifier that organizes chaotic thoughts, boosts focus, and absorbs and neutralizes negative energy and stress. It heightens intuitive abilities and psychic awareness while keeping the mind sharp, clear, and protected.",
    magical: "Place on your desk or workspace to enhance concentration and clear mental fog. Use during study, creative work, or spiritual discernment. Cleanse often as it absorbs negativity readily. Ideal for empaths who need to distinguish their emotions from others'.",
    folklore: "The Romans believed fluorite goblets prevented intoxication. In China, fluorite was used to carve protective vessels and figures for over 300 years. It was called 'the home of the rainbow' in ancient times and was associated with spring, renewal, and mental illumination.",
  },
  {
    name: "Garnet",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Garnet/garnet-mineral-stone-front-black-crystal-36701927.webp",
    chakra: "Root & Heart",
    element: "Fire & Earth",
    zodiac: "Aries, Leo, Capricorn",
    spiritual: "Garnet is the stone of passion, commitment, and life force. It revitalizes energy, stimulates kundalini, and anchors you in your body with fierce, grounded vitality. A stone of devotion and love, it strengthens bonds and ignites the courage to pursue your deepest desires.",
    magical: "Use in spells for passionate love, commitment, and physical vitality. Carry when you need a burst of energy or motivation. Place on the root chakra to awaken kundalini energy. Gift to a lover to strengthen devotion and deepen the bond between you.",
    folklore: "Warriors in ancient Persia engraved garnets with portraits of kings to ensure victory. Medieval travelers wore garnet to protect against accidents. In Norse mythology, garnets lit up Valhalla. Noah was said to have hung a garnet lantern on the ark to navigate through the darkness.",
  },
  {
    name: "Green Aventurine",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/green+aventurine/s-l400.jpg",
    chakra: "Heart",
    element: "Earth & Water",
    zodiac: "Aries, Taurus",
    spiritual: "Green Aventurine is the stone of opportunity, luck, and heart-centered growth. It harmonizes the heart chakra, releases old patterns, and opens the door to new possibilities. A gentle yet powerful prosperity stone, it invites abundance through optimism and forward momentum.",
    magical: "The luckiest stone in the crystal kingdom — carry in your left pocket during games of chance or new ventures. Use in prosperity grids and abundance spells. Bury in your garden to attract good fortune and growth. Wear near the heart to attract loving opportunities.",
    folklore: "The name comes from the Italian 'a ventura' meaning 'by chance.' Tibetan statues were decorated with aventurine eyes to symbolize visionary power. Ancient Chinese emperors associated it with Guanyin, the goddess of compassion. It has been considered a lucky talisman across many world cultures.",
  },
  {
    name: "Hematite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/hematite/images.jpg",
    chakra: "Root",
    element: "Earth & Fire",
    zodiac: "Aries, Capricorn",
    spiritual: "Hematite is the ultimate grounding stone — a dense, magnetic anchor that pulls scattered energy back into the body. It strengthens the connection to Earth, dissolves anxiety, and transforms negative energy into a calm, confident vitality. It fortifies willpower and logical thinking.",
    magical: "Carry when feeling ungrounded, anxious, or overwhelmed. Place at the base of the spine to anchor the root chakra. Use in protection spells and grounding rituals after deep energy work or meditation. Wear during legal matters for strength and fairness.",
    folklore: "Ancient Egyptians placed hematite in tombs to assist the soul's journey. Roman warriors rubbed hematite on their bodies before battle, believing it made them invincible. The word hematite comes from the Greek for 'blood stone' as it leaves a red streak, and it was used in amulets across the ancient world.",
  },
  {
    name: "Howlite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Howlite/pure-abundance-howlite-healing-wand-crystal-shapes-forms-buy-600.webp",
    chakra: "Crown & Third Eye",
    element: "Air",
    zodiac: "Gemini, Virgo",
    spiritual: "Howlite is the stone of patience, awareness, and calm. It quiets a racing mind, eases insomnia, and prepares the soul for deep meditation. A profoundly soothing stone, it dissolves rage, absorbs anger, and teaches the wisdom of patience and emotional attunement.",
    magical: "Place under your pillow to invite restful sleep and meaningful dreams. Use in meditation to silence mental chatter and open spiritual receptivity. Carry when dealing with confrontational people — it absorbs anger without retaining it. Program it as a focus stone for manifestation.",
    folklore: "Howlite was only discovered in 1868 by Canadian geologist Henry How. Despite being a relatively modern discovery, it is often dyed to resemble turquoise or lapis lazuli, and carries similar energies of calm and spiritual awareness, making it a versatile and accessible magical tool.",
  },
  {
    name: "Jade",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Jade/luminous-jade-stone-stockcake.webp",
    chakra: "Heart",
    element: "Earth & Water",
    zodiac: "Aries, Taurus, Gemini, Libra",
    spiritual: "Jade is the stone of harmony, wisdom, and divine luck. Revered for thousands of years as a sacred protector, it nurtures the heart, encourages authenticity, and attracts gentle, lasting prosperity. It filters out negativity and recharges energy with its gentle, nurturing vibration.",
    magical: "One of the most auspicious stones in the world. Wear as a protective talisman. Place a jade frog near your front door to invite wealth. Use in heart-healing rituals and dream work. Carry when making important decisions to access deep inner wisdom.",
    folklore: "In China, jade has been considered the most precious stone for over 7,000 years — more valued than gold. The Aztecs and Maya used jade in royal and religious ceremonies. It was called the 'stone of heaven' and believed to promote longevity. Confucius described it as embodying all human virtues.",
  },
  {
    name: "Kyanite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/kyanite/s202060342624006352_p80_i1_w640.jpeg",
    chakra: "Throat & Third Eye (all chakras)",
    element: "Air & Water",
    zodiac: "Aries, Taurus, Libra",
    spiritual: "Kyanite is one of the only stones that never absorbs negative energy and never needs cleansing. It aligns all chakras automatically, opens the third eye, and acts as a bridge between the conscious mind and higher guidance. A master channel for intuition and psychic communication.",
    magical: "An extraordinary tool for channeling, meditation, and dream work. Use to open psychic channels quickly. Place on the third eye for instant alignment and clarity. Ideal for Reiki practitioners as it amplifies healing energy. Keep near your bed to facilitate astral travel and vivid dreaming.",
    folklore: "In ancient times, kyanite hung from human or animal hair was used as a compass, supposedly always aligning to magnetic north. It was valued by travelers as a directional guide. In metaphysical traditions, blue kyanite is considered a bridge between worlds — a sacred tool of seers and shamans.",
  },
  {
    name: "Labradorite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/labradorite/labradorite-1920x1080-1.jpg",
    chakra: "Third Eye & Crown",
    element: "Air & Water",
    zodiac: "Leo, Scorpio, Sagittarius",
    spiritual: "Labradorite is the stone of magic, transformation, and otherworldly mystery. It awakens dormant psychic abilities, strengthens intuition, and reveals hidden truths. A powerful protective stone, it creates a shield around the aura while opening portals to higher consciousness and inner magic.",
    magical: "The crystal of witches and mystics. Use during divination, tarot reading, and ritual work to amplify psychic receptivity. Hold during meditation to access past lives or spiritual guidance. Wear to maintain energetic protection while doing spiritual work in the world.",
    folklore: "Inuit peoples believed labradorite fell from the frozen fire of the Aurora Borealis — that an ancestor struck the Northern Lights free with a spear and some remained trapped in the stone. Named after Labrador, Canada, where it was discovered in 1770, it has been called 'the temple of the stars.'",
  },
  {
    name: "Lapis Lazuli",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/lapis+lazuli/LapisLazuliWand__71393.jpg",
    chakra: "Third Eye & Throat",
    element: "Air & Water",
    zodiac: "Taurus, Virgo, Libra, Sagittarius",
    spiritual: "Lapis Lazuli is the stone of wisdom, royalty, and divine truth. It activates the higher mind and stimulates the desire for knowledge, truth, and understanding. A stone of vision and prophecy, it opens the third eye and deepens spiritual insight, self-awareness, and inner sovereignty.",
    magical: "Use in rituals for truth-seeking, past life recall, and spiritual vision. Write your deepest questions on paper, place under lapis, and meditate for answers. Wear at the throat and third eye together for powerful communication of spiritual truths. Used in protection amulets since antiquity.",
    folklore: "The ancient Egyptians ground lapis into powder to create ultramarine pigment used in sacred art. Cleopatra used lapis eyeshadow for divine beauty and protection. King Tutankhamun's death mask was inlaid with lapis. The ancient Sumerians believed lapis lazuli contained the soul of the gods.",
  },
  {
    name: "Lepidolite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Lepidolite/Lepidolite.webp",
    chakra: "Heart, Third Eye & Crown",
    element: "Water & Air",
    zodiac: "Libra, Pisces",
    spiritual: "Lepidolite is the stone of transition, calm, and emotional balance. Rich in natural lithium, it stabilizes mood swings, soothes anxiety, and gently eases depression. A profound ally for times of change and uncertainty, it brings deep peace and helps you navigate transformation with grace.",
    magical: "Place under your pillow for peaceful sleep and to ease anxiety. Carry during major life transitions — endings, new beginnings, grief. Use in emotional healing rituals and place on the heart chakra during energy work. A gentle but powerful ally for mental health and emotional resilience.",
    folklore: "Lepidolite was first described in the 18th century and called 'lilalite' for its violet hue. It is often found growing with rose quartz, amplifying its gentle, loving energy. In recent times it has been called the 'grandmother stone' — nurturing, wise, and deeply stabilizing for those navigating difficult passages.",
  },
  {
    name: "Malachite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Malachite/images.jpg",
    chakra: "Heart & Solar Plexus",
    element: "Earth",
    zodiac: "Taurus, Capricorn, Scorpio",
    spiritual: "Malachite is the stone of transformation — a powerful amplifier of all energies that draws out deep-seated emotions, breaks unwanted patterns, and heals the heart with fierce compassion. It reveals what is blocking your growth and catalyzes profound inner change.",
    magical: "Use in transformation rituals and to release toxic relationships or outdated beliefs. Place on the heart chakra to draw out suppressed emotions ready for healing. Powerful for protection — place in the home to guard against negative energies. Use in business spaces to attract prosperity.",
    folklore: "Ancient Egyptians mined malachite in the Sinai from 4000 BCE and carved it into protective amulets and eye cosmetics. Children wore malachite to ward off evil spirits. Medieval Europeans used it to protect against the evil eye. It was associated with Venus and sacred feminine power across many traditions.",
  },
  {
    name: "Moonstone",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/moonstone/moonstone.jpg",
    chakra: "Crown & Third Eye",
    element: "Water",
    zodiac: "Cancer, Libra, Scorpio",
    spiritual: "Moonstone is the sacred stone of the divine feminine, intuition, and lunar cycles. It attunes you to the rhythms of the moon and nature, deepens emotional intelligence, and awakens dormant psychic gifts. A stone of new beginnings, it illuminates the path through inner knowing.",
    magical: "The ultimate moon magic stone. Charge under the full moon and use in all lunar rituals. Wear or carry to enhance intuition and psychic sensitivity. Meditate with moonstone on the new moon to set intentions aligned with your highest self. Gift to new mothers for protection and nurturing.",
    folklore: "In ancient India, moonstone was considered sacred and was displayed on yellow cloth — the only color worthy of it. Romans believed it formed from moonbeams solidified by time. In European folklore, moonstone could reconcile estranged lovers and was given as a gift on the 13th wedding anniversary.",
  },
  {
    name: "Pyrite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Pyrite/istockphoto-918580202-612x612.jpg",
    chakra: "Solar Plexus",
    element: "Fire & Earth",
    zodiac: "Leo, Aries",
    spiritual: "Pyrite is the stone of willpower, manifestation, and bold action. Known as Fool's Gold, it is anything but — it sparks the solar plexus with confidence, courage, and the drive to turn dreams into reality. It shields against negative energy and empowers you to take decisive action.",
    magical: "The ultimate prosperity and protection crystal. Place on your desk or in your workspace to attract abundance and boost productivity. Use in manifestation grids, carry for job interviews, or set next to your vision board to amplify intentions. Rub for a burst of confidence before bold action.",
    folklore: "The name comes from the Greek 'pyr' meaning fire, as it creates sparks when struck against metal. Ancient Incas used polished pyrite as mirrors for scrying. It was used by native North Americans in shamanic healing. Gold miners believed pyrite deposits led to actual gold, associating it strongly with wealth and fortune.",
  },
  {
    name: "Rhodonite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/rhodonite/rhodonite-1920x1080-4.jpg",
    chakra: "Heart",
    element: "Earth & Fire",
    zodiac: "Taurus, Scorpio",
    spiritual: "Rhodonite is the stone of compassionate healing — especially for emotional wounds rooted in betrayal, abandonment, or heartbreak. It clears away emotional scarring, stimulates forgiveness, and nurtures the return of self-love. A grounded heart healer that balances giving and receiving love.",
    magical: "Use in rituals for healing heartbreak, releasing resentment, and cultivating self-worth. Place on the heart chakra for deep emotional healing during energy work. Carry when working through grief or the end of a relationship. Pair with rose quartz for a powerful self-love grid.",
    folklore: "Rhodonite was known in Russia as the 'eagle stone' because eagles were often observed placing pieces in their nests. Russian tsars gave it as a gift of love. In Siberia, it was placed in babies' cradles for protection and given to travelers to ensure safe return. It became the official gemstone of Massachusetts.",
  },
  {
    name: "Rose Quartz",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/rose+quartz/rose-quartz-crystals-isolate-black-background_332246-47.avif",
    chakra: "Heart",
    element: "Water",
    zodiac: "Taurus, Libra",
    spiritual: "Rose Quartz is the stone of unconditional love — the purest vibration of the heart chakra. It radiates soft, healing energy that dissolves emotional wounds, encourages self-acceptance, and opens the heart to give and receive love freely. The universal healer of heartbreak and self-love.",
    magical: "Place in every room to infuse your home with loving energy. Use in love spells, self-love rituals, and heart-healing ceremonies. Sleep with it to invite loving dreams. Place on the heart chakra during meditation to release grief and call in divine love. The cornerstone of every love altar.",
    folklore: "Greek mythology tells of Eros, the god of love, who brought rose quartz to Earth as a gift to give humans the ability to love. Romans used it in facial masks for beauty. Egyptian papyruses recorded using rose quartz face rollers to prevent aging — a practice that has endured 5,000 years into modern beauty rituals.",
  },
  {
    name: "Selenite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/selenite/lamp-raw-selenite-mineral-double-spiral-lamp-air-purifying-home-decor-146343.webp",
    chakra: "Crown & Higher Crown",
    element: "Air & Spirit",
    zodiac: "Taurus, Cancer",
    spiritual: "Selenite is liquid light in crystal form — a high-vibrational stone of clarity, purity, and divine connection. It clears the aura, aligns the spinal column of chakras, and creates a direct link to angelic realms and higher guidance. One of the few stones that cleanses other crystals.",
    magical: "The essential tool for every sacred space. Place selenite on your altar to keep the energy clear and elevated. Use selenite wands to cleanse the aura by combing through the energy field. Charge other crystals by placing them on a selenite plate. Never place in water as it will dissolve.",
    folklore: "Named after Selene, the Greek goddess of the moon, selenite was believed to wax and wane in power with the lunar cycle. Ancient Greeks placed it in windows to harness moonlight. It was associated with Isis in Egyptian tradition and used in temples to invite divine presence into sacred ceremonies.",
  },
  {
    name: "Smoky Quartz",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/smokey+quartz/Smoky-Quartz-A-Misty-Gemstone-Gifted-by-the-Earth-2-1400x784.jpg",
    chakra: "Root & Earth Star",
    element: "Earth",
    zodiac: "Capricorn, Sagittarius",
    spiritual: "Smoky Quartz is the supreme grounding and detoxifying stone. It absorbs and transmutes vast amounts of negative energy, electromagnetic smog, and fear. It gently dissolves anxiety and lifts depression while anchoring you in the present with calm, centered clarity.",
    magical: "Place near electronics to absorb EMF radiation. Use in banishing rituals and to clear spaces of heavy, stagnant energy. Carry when in dark or emotionally heavy environments. Place at the entrance of your home for protection. A powerful anchor in any crystal grid for grounding its energy to Earth.",
    folklore: "In ancient times, smoky quartz was associated with the dark power of Earth gods. The Druids held smoky quartz sacred as a symbol of the dark power of Earth gods. It is the national gemstone of Scotland, known as Cairngorm after the mountains where it was found. Ancient Celts used it to channel the power of earth deities.",
  },
  {
    name: "Sodalite",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/Sodalite/trumbled-sodalite-mineral-stone-front-black-background-oval-shape-mineralogy-esotericism-154708452.webp",
    chakra: "Third Eye & Throat",
    element: "Air & Water",
    zodiac: "Sagittarius",
    spiritual: "Sodalite is the stone of logic, truth, and spiritual perception. It bridges the intellect and the intuitive mind, helping you understand the patterns behind your emotional experiences. It promotes authenticity, clears mental confusion, and deepens self-trust and inner knowing.",
    magical: "Use during study, writing, or any work requiring deep focus and mental clarity. Carry when navigating situations that require both logic and intuition. Place on the third eye during meditation for enhanced psychic perception. Ideal for writers, teachers, and spiritual seekers.",
    folklore: "Sodalite was first brought to notice by Europeans when large deposits were found in Greenland in 1806. The Bolivian Tiwanaku culture used sodalite ornamentally as far back as 1000 BCE. It became fashionable after being discovered in vast quantities in Ontario, Canada, where Princess Patricia of Connaught chose it to adorn Marlborough House in 1901.",
  },
  {
    name: "Sunstone",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/sunstone/polished-sunstone-heliolite-gemstone-dark-macro-shooting-natural-mineral-rock-specimen-polished-sunstone-heliolite-gemstone-103410386.webp",
    chakra: "Sacral & Solar Plexus",
    element: "Fire",
    zodiac: "Leo, Libra",
    spiritual: "Sunstone is the stone of joy, light, and personal empowerment. It carries the warm, radiant energy of the sun — dissolving self-doubt, depression, and codependency while igniting independence, optimism, and the courage to shine your authentic light without apology.",
    magical: "Use in rituals for self-confidence, joy, and abundance. Carry on cloudy days or during winter to lift the spirit. Place on your solar plexus to reclaim personal power and dissolve people-pleasing patterns. Use in solar rituals at noon or during the summer solstice for maximum power.",
    folklore: "Ancient Norse Vikings used sunstone as a navigational tool — it polarizes light and can locate the sun even on overcast days, a property confirmed by modern scientists. It was sacred to the Norse sun god Sol. In ancient Greece, sunstone was said to bring the radiance of the sun god Ra into the physical world.",
  },
  {
    name: "Tiger's Eye",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/tigers+eye/istockphoto-883055018-612x612.jpg",
    chakra: "Root, Sacral & Solar Plexus",
    element: "Earth & Fire",
    zodiac: "Aries, Capricorn, Leo",
    spiritual: "Tiger's Eye is the stone of grounded courage, focused willpower, and integrated vision. It combines earth energy with solar fire to create a stone of bold, decisive action. It sharpens discernment, balances the lower chakras, and helps you see situations clearly without the distortion of fear.",
    magical: "Carry for protection, courage, and mental clarity. Use in prosperity rituals to ground and manifest ambitions into reality. Place on the solar plexus to reclaim personal power. Keep in your car for safe travel and protection. An excellent stone for business ventures and new beginnings requiring boldness.",
    folklore: "Roman soldiers carried engraved tiger's eye into battle for courage and protection. Ancient Egyptians used it to transmit the power of Ra, the sun god, and used it in the eyes of deity statues. In Chinese tradition, tiger's eye was believed to bring good luck and was considered a symbol of courage and integrity throughout Asia.",
  },
  {
    name: "Turquoise",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/turquiose/desktop-wallpaper-turquiose-stones-color-and-mobile-background-turquoise-stone.jpg",
    chakra: "Throat & Third Eye",
    element: "Water & Air",
    zodiac: "Sagittarius, Scorpio, Pisces",
    spiritual: "Turquoise is one of the oldest protection stones in human history — a sacred sky-stone of truth, wholeness, and spiritual attunement. It unites heaven and earth, strengthens communication, and promotes emotional balance and inner calm. A master healer, it aligns all chakras and unites the body, mind, and spirit.",
    magical: "One of the most universally powerful protection and healing stones. Wear at the throat for truth-speaking and authentic self-expression. Place on your altar as a sacred bridge between worlds. Use in healing rituals for the physical body, especially for pain and inflammation. Carry for safe travel and protection.",
    folklore: "Turquoise has been mined for over 6,000 years and was sacred to the ancient Egyptians, Aztecs, Persians, Chinese, and Native Americans. The Aztecs used it to adorn ceremonial masks of the gods. Native American tribes consider it a sacred stone connecting sky and earth. It was one of the first gemstones ever mined.",
  },
  {
    name: "Amethyst",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Crystals/amethyst/images.jpg",
    chakra: "Third Eye & Crown",
    element: "Air",
    zodiac: "Pisces, Virgo, Aquarius",
    spiritual: "Amethyst is the stone of spiritual wisdom and divine connection. It raises your vibration, sharpens intuition, and acts as a natural tranquilizer — dissolving anxiety and inviting deep inner peace. It opens the third eye and crown chakras, bridging the human mind with higher consciousness.",
    magical: "A powerhouse for psychic development, dream work, and meditation. Place under your pillow to encourage prophetic dreams and restful sleep. Use in protection grids, carry during meditation, or wear to stay energetically shielded throughout the day.",
    folklore: "The ancient Greeks believed amethyst could prevent intoxication — the word comes from the Greek 'amethystos,' meaning 'not drunk.' Goblets were carved from it for this reason. Medieval soldiers wore amethyst amulets in battle for protection, and it has long been associated with royalty and the Church.",
  },
];