export const fullMoonEvents2026 = [
  {
    name: "Pink Moon",
    date: "2026-04-01",
    focus: "Hope & New Growth",
    emoji: "🌸",
    color: "rgba(236,72,153,0.5)",
    significance: "Named for early spring blooms, this is a moon of hope and fresh beginnings. We meet to nurture new intentions and open our hearts to new possibilities that are just beginning to take root.",
  },
  {
    name: "Flower Moon",
    date: "2026-05-01",
    focus: "Abundance & Bloom",
    emoji: "🌺",
    color: "rgba(245,158,11,0.5)",
    significance: "A celebration of full visibility and abundance. We gather to honor the beauty we've created and the seeds that have finally sprouted into full, glorious bloom.",
  },
  {
    name: "Blue Moon",
    date: "2026-05-31",
    focus: "Rare Opportunities",
    emoji: "🔵",
    color: "rgba(59,130,246,0.5)",
    significance: "A rare bonus second moon in a single month. We meet to seize rare opportunities and perform deep resets on energy that no longer serves — a cosmic invitation to go further.",
  },
  {
    name: "Strawberry Moon",
    date: "2026-06-29",
    focus: "Fulfillment & Sweetness",
    emoji: "🍓",
    color: "rgba(220,38,38,0.5)",
    significance: "The peak of the harvest and the peak of sweetness. We socialize and celebrate the sweet fruits of our labor from the first half of the year. A time of joy, connection, and gratitude.",
  },
  {
    name: "Buck Moon",
    date: "2026-07-29",
    focus: "Strength & Vitality",
    emoji: "🦌",
    color: "rgba(6,182,212,0.5)",
    significance: "Antlers are in full growth. We meet to harness our personal power and stand firm in our spiritual authority. This is a moon of bold strength and unapologetic vitality.",
  },
  {
    name: "Sturgeon Moon",
    date: "2026-08-28",
    focus: "Deep Intuition",
    emoji: "🐟",
    color: "rgba(99,102,241,0.5)",
    significance: "A connection to the ancient depths. This circle focuses on diving into our subconscious and trusting the wisdom within. What lives in your depths is ready to rise.",
  },
  {
    name: "Harvest Moon",
    date: "2026-09-26",
    focus: "Grounding & Stability",
    emoji: "🌾",
    color: "rgba(234,88,12,0.5)",
    significance: "The moon closest to the Equinox. We meet to ground our energy and prepare our inner storehouse for the colder months ahead. Stability is a spiritual practice.",
  },
  {
    name: "Hunter's Moon",
    date: "2026-10-25",
    focus: "Clarity & Focus",
    emoji: "🏹",
    color: "rgba(22,163,74,0.5)",
    significance: "Time to hunt for truth. We gather to sharpen our spiritual vision and prioritize what truly matters for our transformation. What will you choose to pursue?",
  },
  {
    name: "Beaver Moon",
    date: "2026-11-24",
    focus: "Preparation & Shelter",
    emoji: "🦫",
    color: "rgba(168,85,247,0.5)",
    significance: "Building inner foundations. We focus on spiritual protection and creating a safe inner home for the winter months — a sanctuary within yourself.",
  },
  {
    name: "Cold Moon",
    date: "2026-12-23",
    focus: "Reflection & Closure",
    emoji: "❄️",
    color: "rgba(148,163,184,0.5)",
    significance: "The year's final glow. A quiet and sacred circle for reviewing our journey, finding peace in the darkness, and resting into all we have become.",
  },
];