export const fullMoonEvents2026 = [
  {
    name: "Worm Moon",
    date: "2026-03-28",
    zodiac: "Libra ♎",
    emoji: "🌕",
    color: "rgba(124,58,237,0.5)",
    significance: "A moon of balance and partnership. The Worm Moon in Libra illuminates where harmony is needed in your relationships. Set intentions around justice, beauty, and finding equilibrium between giving and receiving.",
  },
  {
    name: "Pink Moon",
    date: "2026-04-26",
    zodiac: "Scorpio ♏",
    emoji: "🌸",
    color: "rgba(219,39,119,0.5)",
    significance: "Named for spring phlox, this Scorpio moon demands deep transformation. Release toxic patterns, embrace vulnerability, and let the old self die so the empowered you can bloom.",
  },
  {
    name: "Flower Moon",
    date: "2026-05-26",
    zodiac: "Sagittarius ♐",
    emoji: "🌺",
    color: "rgba(245,158,11,0.5)",
    significance: "Adventure and expansion burst forth. The Flower Moon in Sagittarius inspires bold leaps of faith, travel dreams, and philosophical breakthroughs. Your truth wants to be spoken.",
  },
  {
    name: "Strawberry Moon",
    date: "2026-06-24",
    zodiac: "Capricorn ♑",
    emoji: "🍓",
    color: "rgba(220,38,38,0.5)",
    significance: "Sweetness meets structure. This Capricorn moon helps you build lasting foundations for your dreams. Harvest the rewards of discipline and set goals that honor both ambition and soul.",
  },
  {
    name: "Buck Moon",
    date: "2026-07-24",
    zodiac: "Aquarius ♒",
    emoji: "🦌",
    color: "rgba(6,182,212,0.5)",
    significance: "The Buck Moon in Aquarius calls you to break free from convention. Embrace your inner rebel, connect with your community, and channel innovation into humanitarian pursuits.",
  },
  {
    name: "Sturgeon Moon",
    date: "2026-08-22",
    zodiac: "Pisces ♓",
    emoji: "🐟",
    color: "rgba(99,102,241,0.5)",
    significance: "Deep waters of intuition run strong. This Pisces moon amplifies psychic abilities and creative visions. Surrender to the flow, practice dream work, and trust what you feel.",
  },
  {
    name: "Harvest Moon",
    date: "2026-09-21",
    zodiac: "Aries ♈",
    emoji: "🌾",
    color: "rgba(234,88,12,0.5)",
    significance: "Fire meets fruition. The Harvest Moon in Aries empowers courageous action. Reap what you've sown, ignite new passions, and step boldly into your personal power.",
  },
  {
    name: "Hunter's Moon",
    date: "2026-10-20",
    zodiac: "Taurus ♉",
    emoji: "🏹",
    color: "rgba(22,163,74,0.5)",
    significance: "Ground and protect what matters. This Taurus moon asks you to nourish your body, tend your garden, and fiercely guard your peace. Abundance is your birthright.",
  },
  {
    name: "Beaver Moon",
    date: "2026-11-19",
    zodiac: "Gemini ♊",
    emoji: "🦫",
    color: "rgba(168,85,247,0.5)",
    significance: "Prepare and communicate. The Beaver Moon in Gemini sharpens your words and clarifies your message. Journal, have important conversations, and build bridges before winter.",
  },
  {
    name: "Cold Moon",
    date: "2026-12-18",
    zodiac: "Cancer ♋",
    emoji: "❄️",
    color: "rgba(148,163,184,0.5)",
    significance: "The year's final full moon in Cancer wraps you in emotional healing. Come home to yourself. Honor your ancestors, nurture your inner child, and release what no longer serves your highest good.",
  },
];