export const libraryHerbs = [
  {
    name: "Basil",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/basilherb/basil.png",
    element: "Fire",
    uses: "Love, prosperity, protection, purification",
    magical: "Used in money spells and to attract love. Sprinkle at doorways to invite prosperity. Burn to banish negativity.",
    folklore: "Ancient Greeks believed basil could only grow if you screamed curses while sowing. In Italy it was a token of love — a woman placing basil on her windowsill signaled she was ready to receive a suitor.",
  },
  {
    name: "Bay Laurel",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/bayleaf/baylaurel.png",
    element: "Fire",
    uses: "Psychic vision, wishes, protection, success",
    magical: "Write a wish on a bay leaf and burn it to send intentions to the universe. Carry for protection and to enhance psychic abilities.",
    folklore: "Sacred to Apollo, bay laurel crowned victors and oracles at Delphi. Priestesses chewed the leaves to enter prophetic trance. It was hung above doorways to ward off evil and plague.",
  },
  {
    name: "Belladonna",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/belladonnaplant/belladonna.png",
    element: "Water",
    uses: "Astral projection, shadow work, transformation (toxic — use with extreme caution)",
    magical: "A powerful baneful herb sacred to Hecate. Used historically in flying ointments by witches for astral travel. A plant of boundaries, death, and rebirth.",
    folklore: "Known as 'Deadly Nightshade,' its name means 'beautiful woman' in Italian — ladies used the juice to dilate pupils for a glamorous look. It was said to be tended by the devil himself.",
  },
  {
    name: "Calendula",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/calendula/calendula.png",
    element: "Fire",
    uses: "Sun magic, protection, legal matters, psychic dreams",
    magical: "A solar herb that radiates warmth and victory. Strewn under beds to induce prophetic dreams. Incorporated into spells for legal success and protection from negativity.",
    folklore: "Called the 'herb of the sun,' calendula was used by ancient Egyptians for rejuvenation. Medieval Europeans believed it could reveal faeries and ward off evil. It follows the sun's movement across the sky.",
  },
  {
    name: "Catnip",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/catnip/Untitled.png",
    element: "Water",
    uses: "Cat magic, love, beauty, happiness, familiar bonding",
    magical: "Burned or carried to attract love and good luck. Used to strengthen bonds with animal familiars, especially cats. Infuse in sachets for joy and feminine energy.",
    folklore: "In folk magic catnip was given as a gift from witch to witch, symbolizing their shared bond. It was also used in love sachets alongside rose petals to draw in a romantic partner.",
  },
  {
    name: "Cedar",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/cedar/cedarsmudge.png",
    element: "Earth / Fire",
    uses: "Purification, protection, healing, grounding",
    magical: "Burned in smudging rituals to cleanse and protect spaces. Cedar calls in ancient ancestral wisdom and grounds spiritual energy into the physical. A powerful protector of the home.",
    folklore: "Sacred to many Indigenous traditions, cedar is considered a grandfather plant — one of the first medicines given to humanity. The Celts associated it with immortality and planted it near sacred groves.",
  },
  {
    name: "Chamomile",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/chamomileherb/chamomile.png",
    element: "Water",
    uses: "Sleep, calm, money luck, purification, love",
    magical: "Wash your hands in chamomile tea before gambling or money rituals to attract luck. Used in sleep sachets to prevent nightmares. A gentle solar herb for healing spells.",
    folklore: "The Egyptians dedicated chamomile to the sun god Ra and used it to treat fevers. In Germany it was called 'alles zutraut' (capable of anything). Planting it in the garden was said to attract abundance to the whole household.",
  },
  {
    name: "Cinnamon",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/cinnamon/cinnamons.png",
    element: "Fire",
    uses: "Prosperity, success, love, psychic enhancement, speed",
    magical: "One of the most potent magical accelerants — it speeds up the manifestation of any spell. Burn to raise vibration or add to prosperity sachets. Excellent for love and passion work.",
    folklore: "In ancient Rome cinnamon was worth more than silver. Arabian traders invented fantastical tales of it being guarded by giant birds to keep its source secret. It was burned as incense in temples across the ancient world.",
  },
  {
    name: "Clove",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/clove/cloves.png",
    element: "Fire",
    uses: "Protection, banishing, love, money, clarity",
    magical: "Burn to stop gossip and dispel negativity. Carry cloves to attract the opposite sex or drive away hostile forces. Clove smoke purifies and empowers sacred spaces.",
    folklore: "In the Middle Ages cloves were hung in homes to ward off the evil eye. They were stuffed into oranges and gifted as love charms. Pirates and sailors wore cloves as protective amulets on long voyages.",
  },
  {
    name: "Comfrey",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/comfreys/comfrey.png",
    element: "Earth / Water",
    uses: "Safe travel, money, stability, healing",
    magical: "Place in luggage to protect travellers. Carry the root for good luck and financial stability. Used in money spells for long-lasting, grounded prosperity.",
    folklore: "Known as 'knitbone,' comfrey was believed to knit broken bones together magically. It was said to grow wherever a wise woman had walked. Travelers placed it in their shoes to ensure they arrived safely.",
  },
  {
    name: "Dandelion",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/dandelion/wishing.png",
    element: "Air",
    uses: "Wishes, divination, communication with spirit, resilience",
    magical: "Blow dandelion seeds while holding a wish — the wind carries it to spirit. The root tea enhances psychic dreams. A symbol of transformation and the magic of new beginnings from humble ground.",
    folklore: "Dandelion clocks have been used to tell the time and count lovers' faithfulness since medieval times. In Celtic tradition it was believed to hold the power to grant wishes and communicate between worlds. Its persistence in growing is seen as a symbol of unstoppable will.",
  },
  {
    name: "Dragon's Blood",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/dragons+blood/Untitled.png",
    element: "Fire",
    uses: "Power amplification, protection, love, banishing",
    magical: "One of the most powerful magical resins. Amplifies the intention of any spell it is added to. Burned alone to banish evil or mixed with other herbs to multiply their power tenfold.",
    folklore: "Dragon's Blood resin comes from the Dracaena tree and has been traded since antiquity. Medieval alchemists believed it carried the literal essence of dragon's fire. It was used to ink magical contracts and seal spells permanently.",
  },
  {
    name: "Echinacea",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/echinaceaherb/theeherb.png",
    element: "Earth",
    uses: "Healing, strength, offerings, immune magic",
    magical: "Used as an offering to strengthen spells. Associated with vitality and resilience. Add to healing sachets or burn to empower workings that need lasting strength.",
    folklore: "Sacred to Native American tribes of the Great Plains who used it medicinally and ritually. The Cherokee used it to strengthen endurance in vision quests. Its spiky seed head was seen as resembling the sun — a symbol of life force.",
  },
  {
    name: "Elderflower",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/elderflowers/elderflower.png",
    element: "Water / Air",
    uses: "Faerie magic, protection, healing, blessings, transitions",
    magical: "The Elder tree is a portal between worlds. Elderflower summons faerie blessings and protective spirits. Used at Samhain to commune with the dead and at Beltane to invite summer's abundance.",
    folklore: "In European tradition the Elder Mother (Hyldemor) lives within the tree and must be asked permission before cutting any branches. Burning elder was considered deeply unlucky. It was planted near homes to protect against lightning and malevolent witches.",
  },
  {
    name: "Fennel",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/fennel/fennelherb.png",
    element: "Fire",
    uses: "Protection, courage, healing, longevity",
    magical: "Hang above doors at Midsummer to ward off evil spirits. Carry fennel seeds for courage and clarity. Used in protective sachets to guard against hexes and curses.",
    folklore: "Ancient Greeks believed fennel was the means by which Prometheus carried fire from the gods to humanity in a hollow fennel stalk. Roman soldiers ate fennel before battle to instill courage and strength.",
  },
  {
    name: "Frankincense",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/frankincense/Untitled.png",
    element: "Fire",
    uses: "Purification, consecration, spiritual elevation, meditation",
    magical: "The most sacred of ritual incenses. Burned to purify space, elevate vibration, and invite divine presence. Frankincense opens the crown chakra and creates a direct channel to the divine.",
    folklore: "Burned in the temples of ancient Egypt, Babylon, and Israel for millennia. The Magi carried it as a sacred gift. Its smoke was believed to carry prayers directly to the gods. Used in the embalming process to consecrate and honor the dead.",
  },
  {
    name: "Ginger",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/ginger/Untitled.png",
    element: "Fire",
    uses: "Love, power, success, money, speed",
    magical: "A fiery catalyst for all magic. Adds heat, speed, and passionate energy to spells. Used in love magic to ignite desire and in money magic to accelerate financial flow.",
    folklore: "In Asia ginger root was used as a lucky charm for centuries. Sailors planted it on ships to ward off scurvy and ill fortune at sea. Medieval Europeans ate gingerbread men to attract love — baking a lover's image inside.",
  },
  {
    name: "Hawthorn",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hawthrons/hawthorn.png",
    element: "Fire",
    uses: "Faerie magic, heart healing, fertility, protection",
    magical: "A deeply powerful faerie tree — never cut hawthorn without leaving an offering. Worn at Beltane for fertility blessings. The thorns can be used in protective charms or to mark magical boundaries.",
    folklore: "The hawthorn is one of the sacred faerie triad alongside oak and ash. In Ireland, lone hawthorn trees in fields were considered faerie trees and would never be cut lest great misfortune follow. It is said the Holy Thorn at Glastonbury was planted by Joseph of Arimathea.",
  },
  {
    name: "Hemlock",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hemlock/hemlocks.png",
    element: "Water / Saturn",
    uses: "Banishing, binding, shadow magic (toxic — do not ingest)",
    magical: "A baneful herb of Saturn used in binding spells and to break destructive cycles. Historically used in spells to stop enemies. Approach only with deep respect and protective intention.",
    folklore: "Most infamous for the execution of Socrates. In witchcraft tradition hemlock was used to anoint tools used in banishing. Associated with the underworld, it was planted at crossroads to mark the boundary between the living and the dead.",
  },
  {
    name: "Holly",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hollys/holly.png",
    element: "Fire",
    uses: "Protection, luck, winter magic, dream work",
    magical: "Holly protects against lightning, poison, and evil spirits. Brought into the home at Yule to shelter nature spirits during winter. Holly wood is used for wands of power and authority.",
    folklore: "The Holly King rules the dark half of the year and battles the Oak King at the solstices. In Celtic myth holly never loses its power — it is evergreen and eternal. Throwing holly at wild beasts was said to make them lie down peacefully.",
  },
  {
    name: "Hyssop",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/hyssops/hyssop.png",
    element: "Fire",
    uses: "Purification, cleansing, forgiveness, lifting hexes",
    magical: "One of the primary purification herbs in Western magic. Burned or sprinkled as holy water for deep cleansing of body, spirit, and space. Especially potent for releasing guilt and shame.",
    folklore: "Referenced in the Bible for ritual purification: 'Purge me with hyssop and I shall be clean.' The ancient Hebrews used it to cleanse doorposts. Medieval monks carried it to ward off plague and evil influence.",
  },
  {
    name: "Ivy",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/ivyplant/ivy.png",
    element: "Water",
    uses: "Fidelity, binding love, protection, persistence",
    magical: "Ivy represents unbreakable bonds and eternal commitment. Used in handfasting and love binding spells. Its clinging nature makes it ideal for spells of persistence and fidelity.",
    folklore: "Sacred to Dionysus, ivy was woven into the god's crown and worn by revellers. In Norse tradition ivy was a symbol of the feminine divine. A bride who wore ivy was assured of lasting love. Ivy growing on a house was said to protect it from all harm.",
  },
  {
    name: "Jasmine",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/jasmine/jasmineflower.png",
    element: "Water",
    uses: "Love, dreams, moon magic, sensuality, prophetic vision",
    magical: "A lunar herb of deep feminine power. Burned at night to attract love and invoke prophetic dreams. Jasmine oil anointed on the third eye enhances psychic sensitivity.",
    folklore: "In Persian tradition jasmine was called 'gift from God.' Indian brides are crowned with jasmine to bless their union. In Victorian England jasmine was gifted to communicate love that cannot be spoken aloud.",
  },
  {
    name: "Juniper",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/juniper/junipers.png",
    element: "Fire",
    uses: "Protection, anti-theft, health, love, exorcism",
    magical: "A fierce protector. Hung above doorways to prevent theft and repel evil. Burned to banish negative entities. Juniper berries carried to attract love and protect against psychic attack.",
    folklore: "In ancient Egypt juniper was used in embalming rituals to protect the soul in the afterlife. Tibetan monks burn it in purification ceremonies. In Europe it was burned at Samhain to guide home the spirits of beloved dead.",
  },
  {
    name: "Lavender",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/lavender/Untitled.png",
    element: "Air",
    uses: "Peace, sleep, purification, love, happiness",
    magical: "One of the most beloved magical herbs. Placed in sachets under pillows for peaceful sleep and healing dreams. Used in love spells, purification rituals, and to create a calm sacred space.",
    folklore: "Romans added lavender to bath water — the word lavender comes from 'lavare' (to wash). It was believed to tame lions and tigers. A sprig of lavender worn at the wrist was said to allow one to see ghosts.",
  },
  {
    name: "Lemon Balm",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/lemonbalms/lemonbalm.png",
    element: "Water",
    uses: "Love, success, healing, calming anxiety, communication",
    magical: "A gentle but powerful herb for emotional healing and attracting love. Rub lemon balm on candles in success rituals. Carry to soothe anxiety and invite joyful communication.",
    folklore: "Paracelsus called it the 'elixir of life.' The 14th-century herbalist John Evelyn declared: 'Balm is sovereign for the brain, strengthening the memory and powerfully chasing away melancholy.' Beekeepers rubbed it on hives to keep bees happy and attract new swarms.",
  },
  {
    name: "Mandrake",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mandrake/mandrakeroot.png",
    element: "Earth / Fire",
    uses: "Power, protection, fertility, manifestation, cursing and uncursing",
    magical: "One of the most mythically powerful magical plants. The root resembles a human form and is used as a magical poppet. Kept on an altar as a familiar spirit, mandrake amplifies every working near it.",
    folklore: "Legend holds that mandrake screams when uprooted, and the scream kills all who hear it. To harvest it safely one was to plug their ears with wax and tie a dog to the plant at midnight. It was a primary ingredient in the medieval witch's flying ointment.",
  },
  {
    name: "Mint",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mint/itsmint.png",
    element: "Air",
    uses: "Money, travel, healing, protection, cleansing",
    magical: "Place mint in wallets to attract money. Burn to purify a space before ritual. Spearmint heightens mental clarity; peppermint amplifies protective energy. Rub fresh mint on skin before important meetings.",
    folklore: "In Greek mythology the nymph Minthe was transformed into the plant by a jealous goddess. Romans scattered mint on floors of guest rooms to energize visitors. It was placed in wine to test for poison.",
  },
  {
    name: "Mistletoe",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mint/itsmint.png",
    element: "Air",
    uses: "Protection, love, fertility, hunting luck, healing",
    magical: "The sacred plant of the Druids, cut only with a golden sickle at Winter Solstice. Mistletoe never touches the earth — it grows between worlds and therefore has power in all realms. Used to make all-heal medicine.",
    folklore: "Druids believed mistletoe fell from lightning — a gift from the sun to the oak. In Norse myth Baldur was slain by a mistletoe dart; when restored to life mistletoe was made sacred to love. The kiss under the mistletoe originated from this myth of love's triumph over death.",
  },
  {
    name: "Mugwort",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/mugwortherb/mugwort.png",
    element: "Earth / Air",
    uses: "Psychic vision, lucid dreaming, astral travel, divination",
    magical: "The premier herb of psychic work and dream magic. Burn or place under a pillow to induce vivid, prophetic dreams. Use to consecrate scrying mirrors and divination tools. Activates the third eye.",
    folklore: "Called 'Sailor's Tobacco' and 'Mother of Herbs,' mugwort was placed in shoes by Roman soldiers to ease long marches. Anglo-Saxons counted it as the first of the Nine Sacred Herbs. Witches rubbed mugwort salve on their eyes to see into the spirit world.",
  },
  {
    name: "Myrrh",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/myrrh/Untitled.png",
    element: "Water",
    uses: "Healing, purification, protection, connection to ancestors",
    magical: "A sacred resin of protection and transformation. Burned alongside frankincense to purify and consecrate space. Myrrh deepens meditation, honors the dead, and supports shadow work.",
    folklore: "In Greek myth Myrrha was transformed into the myrrh tree. The resin was used by Isis to resurrect Osiris. Ancient Egyptians burned myrrh at noon as an offering to the sun god Ra. It was traded along the incense road of Arabia for 4,000 years.",
  },
  {
    name: "Nettle",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/nettle/nettlesting.png",
    element: "Fire",
    uses: "Protection, lust, healing, breaking hexes",
    magical: "A fierce herb of protection — stuff a poppet with nettle to break a curse. Throw into fire while visualizing fears to dispel them. Carry to remove a hex and send it back to its source.",
    folklore: "In Norse tradition nettles were sacred to Thor and used in thunderstorm protection magic. The fae were said to use nettle cloth. Scottish Highlanders believed nettle only grew over the bodies of the dead and would plant it to honor their ancestors.",
  },
  {
    name: "Oak",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/nettle/nettlesting.png",
    element: "Fire / Earth",
    uses: "Strength, protection, wisdom, endurance, abundance",
    magical: "The king of the sacred grove. Oak acorns carried for luck, longevity, and fertility. Oak wood makes the most powerful wands for commanding magic. Spells cast under an oak are powerfully amplified.",
    folklore: "The oak was the most sacred tree of the Druids — their name may derive from 'dru' (oak) and 'wid' (wisdom): those who know the oak. In Norse myth Yggdrasil, the world tree, was an ash-oak hybrid. Zeus's sacred grove at Dodona was entirely of oaks whose rustling leaves were divine prophecy.",
  },
  {
    name: "Patchouli",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/patchouli/Untitled.png",
    element: "Earth",
    uses: "Money, fertility, lust, grounding, banishing",
    magical: "A deeply earthy scent for grounding and abundance magic. Add to money sachets or rub on cash before spending. Used in love and fertility rituals and to anchor spiritual energy into physical form.",
    folklore: "In the Victorian era fine Indian cashmere shawls were packed with patchouli leaves to deter moths — the smell became associated with wealth and luxury. Indian ink was scented with patchouli, and traders used it to verify authenticity of goods.",
  },
  {
    name: "Rosemary",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/rosemary/rosemary.png",
    element: "Fire",
    uses: "Memory, protection, love, purification, mental clarity",
    magical: "Called the 'herb of remembrance.' Burn to cleanse a space of negative energy. Used in protection amulets and love spells. A sprig under the pillow keeps nightmares away and sharpens the mind.",
    folklore: "Mourners at Greek and Roman funerals threw rosemary into graves as a symbol of remembrance. Brides wore rosemary in their wedding crowns. In Tudor England it was placed beneath a child's bed to prevent faeries from stealing the baby in the night.",
  },
  {
    name: "Rose",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/roses/rose.png",
    element: "Water",
    uses: "Love, beauty, psychic power, healing, divination",
    magical: "The supreme herb of love magic. Each color carries different magic: red for passion, pink for self-love, white for purity, black for banishing. Rose petals cast in a circle increase magical potency.",
    folklore: "Sacred to Aphrodite, roses are the oldest cultivated flower. The Romans showered rose petals over lovers and heroes. Sub rosa ('under the rose') meant a secret — roses carved in meeting rooms signified that all said was confidential. In alchemy the rose symbolized the perfection of the Great Work.",
  },
  {
    name: "Rowan",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/rowans/rowan.png",
    element: "Fire",
    uses: "Protection, psychic power, success, anti-enchantment",
    magical: "One of the most protective trees in Celtic magic. Rowan twigs tied with red thread into an equal-armed cross guard against all enchantments. Used to protect livestock, homes, and sacred wells.",
    folklore: "The Celts called rowan 'the tree of life' and planted it near stone circles. In Scottish Highland tradition a rowan growing near a house prevented witches from entering. Rowan stakes were used to pin down the bodies of suspected vampires and malevolent dead.",
  },
  {
    name: "Sage",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/sage/Untitled.png",
    element: "Earth / Air",
    uses: "Purification, wisdom, longevity, protection, cleansing",
    magical: "The most widely used cleansing herb in Western practice. Burning sage (smudging) removes stagnant energy and negative entities from a space. Write wishes on sage leaves and burn them to manifest desires.",
    folklore: "The Latin name Salvia comes from 'salvere' — to be saved or healed. A medieval proverb asked: 'Why should a man die who has sage in his garden?' The ancient Romans considered sage so sacred it was harvested with special tools by priests in white robes.",
  },
  {
    name: "Sandalwood",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/sandalwood/sandalwoods.png",
    element: "Water / Air",
    uses: "Meditation, healing, spiritual elevation, manifestation, consecration",
    magical: "A sacred wood used across Hindu, Buddhist, and Western traditions. Burned to clear the mind for deep meditation. Write wishes on sandalwood chips and burn to send them to the divine. Sandalwood paste marks sacred objects.",
    folklore: "Sandalwood has been used in Hindu temples for over 4,000 years. In Ayurveda it was the supreme medicine for cooling the body and calming the mind. Ancient Egyptians used sandalwood oil in the embalming process to ease the soul's passage into the afterlife.",
  },
  {
    name: "St. John's Wort",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/stjohnswort/st+johns+wort.png",
    element: "Fire",
    uses: "Protection, solar magic, anti-depression, dispelling darkness",
    magical: "A powerfully solar herb harvested at Midsummer. Hung above doors at Litha to protect against evil and lightning. Its bright yellow flowers are burned to banish depression and fear.",
    folklore: "Named for St. John the Baptist, whose feast day (Midsummer) coincides with its bloom. Ancient Greeks hung it above religious icons to ward off evil spirits. Red spots on its leaves were said to symbolize the blood of John the Baptist. Burning it at Midsummer bonfires was a major ritual across Europe.",
  },
  {
    name: "Thyme",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/thyme/herbsthyme.png",
    element: "Air / Water",
    uses: "Courage, purification, sleep, psychic ability, fairy sight",
    magical: "Placed in a sachet under the pillow for restful sleep and fairy dreams. Burned to purify a space. Carrying thyme grants courage. A poultice placed on the eyelids on Beltane Eve was said to allow sight of the faeries.",
    folklore: "Greek soldiers bathed in thyme water before battle for courage. In the Middle Ages ladies embroidered thyme onto scarves given to knights. Wild thyme growing on fairy mounds marks a faerie portal — sit within a ring of thyme on Midsummer to see the fairy host.",
  },
  {
    name: "Valerian",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/valerian/valarian.png",
    element: "Water",
    uses: "Sleep, love, protection, purification, grounding",
    magical: "Used in protective and love sachets. The scent strongly attracts cats (and was said to attract rats — the Pied Piper may have used valerian). Valerian root placed in the home brings harmony and restful energy.",
    folklore: "Medieval herbalists called it 'all-heal.' In some traditions it was used as a love potion — a woman wearing valerian would attract swarms of male admirers. During WWII it was used to treat shell shock and anxiety.",
  },
  {
    name: "Vervain",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/vervains/vervain.png",
    element: "Earth / Air",
    uses: "Protection, love, purification, peace, creativity",
    magical: "One of the most sacred Druidic herbs. Called 'Herba Sacra' by the Romans. Worn as a wreath by diplomatic envoys for protection. Vervain anointed on the body opens the senses to spiritual vision.",
    folklore: "The Romans cleared altars with vervain before ceremonies. Druids harvested it at Sirius's rising, when neither sun nor moon was out. Medieval Europeans believed vervain grew on the hill of Calvary and stopped Christ's bleeding — making it a herb of miraculous healing.",
  },
  {
    name: "Willow",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/willowleaves/willow.png",
    element: "Water",
    uses: "Moon magic, grief, psychic ability, love, flexibility",
    magical: "Sacred to the moon and the goddess Hecate. Willow wands are ideal for lunar and water magic. Used in grief rituals to ease sorrow and in love spells to weave flexibility and deep feeling. Sitting under a willow at midnight invites visions.",
    folklore: "The Celts associated willow with the otherworld and the lunar cycle. In Greek myth willow was sacred to Circe, Hecate, and Persephone. In China willow was used to sweep away evil spirits at funerals. The 'Weeping Willow' weeps for lost souls and remembers all sorrows.",
  },
  {
    name: "Wolfsbane",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/wolfsbane/Untitled.png",
    element: "Water / Saturn",
    uses: "Werewolf protection, invisibility, banishing, transformation (toxic — do not handle)",
    magical: "A deeply baneful herb of Saturn and Hecate. Historically used in witch's flying ointments for shapeshifting magic. In protective circles it guards against transformation and lycanthropic attack.",
    folklore: "Aconite (wolfsbane) was said to have sprung from the drool of Cerberus when Hercules dragged him from the underworld. Viking warriors called it Thor's Helmet and used it to poison arrowheads. In werewolf folklore, wolfsbane both caused and cured lycanthropy depending on the spell.",
  },
  {
    name: "Wormwood",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/wormwoods/wormwood.png",
    element: "Fire / Air",
    uses: "Psychic vision, summoning spirits, love, travel protection",
    magical: "Burned to summon spirits and enhance clairvoyance. Carried to protect travellers from danger. Combined with mugwort in a sachet placed under the pillow for vivid spirit-contact dreams.",
    folklore: "The key ingredient in Absinthe — 'The Green Fairy' — wormwood was said to unlock the visionary imagination. Named 'Artemisia absinthium' after Artemis, it was given to women in childbirth. The biblical 'Wormwood star' in Revelation represents bitterness — wormwood makes water undrinkable.",
  },
  {
    name: "Yarrow",
    image: "https://crystalphotosforveya.s3.us-east-2.amazonaws.com/Herbs/yarrow/yarrows.png",
    element: "Water / Air",
    uses: "Divination, courage, love, healing, psychic protection",
    magical: "The classic herb of the I Ching — yarrow stalks have been used for divination for 3,000 years. Carried in a bride's bouquet to ensure seven years of love. Protects against negative psychic energy.",
    folklore: "Named Achillea millefolium — Achilles used yarrow to staunch the wounds of his soldiers. Native Americans called it 'life medicine.' In Orkney it was called 'mellow' and a sprig held over the eyes was said to grant second sight.",
  },
];