export const journalPrompts = {
  inner_child: {
    label: "Inner Child",
    emoji: "🧒",
    color: "bg-pink-500/10 border-pink-500/20",
    prompts: [
      "What did your younger self need to hear that they never did?",
      "Describe a moment from childhood where you felt truly safe and loved.",
      "Write a letter to your 7-year-old self. What would you tell them?",
      "What childhood joy have you abandoned? How can you reclaim it?",
      "What promise did you make to yourself as a child that you've kept — or broken?",
      "If your inner child could speak right now, what would they ask for?",
      "Describe the home you wished you grew up in. What feelings does it evoke?",
    ],
  },
  triggers: {
    label: "Triggers & Patterns",
    emoji: "⚡",
    color: "bg-amber-500/10 border-amber-500/20",
    prompts: [
      "What situation triggered you recently? Trace it back — what was the original wound?",
      "When someone ignores you, what story does your mind tell? Where did this story begin?",
      "What pattern do you keep repeating in relationships? What does it protect you from?",
      "Describe a recent moment of anger. Underneath it, what emotion was actually present?",
      "What type of person triggers you the most? What do they mirror back to you?",
      "When you feel the urge to control, what fear is driving it?",
      "What boundary did you fail to set recently? What held you back?",
    ],
  },
  forgiveness: {
    label: "Self-Forgiveness",
    emoji: "🕊️",
    color: "bg-violet-500/10 border-violet-500/20",
    prompts: [
      "What do you need to forgive yourself for today?",
      "Write about a mistake you keep punishing yourself for. Then rewrite the story with compassion.",
      "If your best friend made the same mistake you did, what would you tell them?",
      "What would it feel like to fully release the guilt you carry?",
      "List three things you did wrong. Now list what each one taught you.",
      "Where in your body do you hold unforgiveness? Describe the sensation.",
      "Write: 'I forgive myself for ________' and let whatever needs to come, come.",
    ],
  },
  dreams: {
    label: "Dream Work",
    emoji: "🌙",
    color: "bg-indigo-500/10 border-indigo-500/20",
    prompts: [
      "Describe last night's dream in as much detail as possible.",
      "What recurring dream symbol keeps appearing? What might it mean for you?",
      "If the characters in your dream were parts of yourself, what would each represent?",
      "Write a dialogue with a figure from your dream. What do they want to tell you?",
      "What emotion did you wake up with? Where in your waking life does this emotion live?",
      "Describe a dream that felt prophetic or deeply meaningful.",
      "If you could re-enter a dream, which would it be and what would you change?",
    ],
  },
  shadow: {
    label: "Shadow Work",
    emoji: "🖤",
    color: "bg-gray-500/10 border-gray-500/20",
    prompts: [
      "What trait in others makes you most uncomfortable? Do you see it in yourself?",
      "What part of yourself do you hide from the world? Why?",
      "Describe your shadow self. Give them a name. What do they want?",
      "What lie do you tell yourself most often? What truth does it mask?",
      "What would you do if nobody could judge you?",
      "What are you most afraid of others finding out about you?",
      "Where do you self-sabotage? What are you really protecting?",
    ],
  },
};